USE Kyoku;

INSERT IGNORE INTO Genre (id,`name`,cover) VALUES
(1, "Acoustic", "rawGenreCover/Acoustic/"),
(2, "Actor", "rawGenreCover/Actor/"),
(3, "Actress", "rawGenreCover/Actress/"),
(4, "Afro-Pop", "rawGenreCover/Afro-Pop/"),
(5, "Afrobeat", "rawGenreCover/Afrobeat/"),
(6, "Albanian", "rawGenreCover/Albanian/"),
(7, "Alternative", "rawGenreCover/Alternative/"),
(8, "Arabic", "rawGenreCover/Arabic/"),
(9, "Armenian", "rawGenreCover/Armenian/"),
(10, "Assamese", "rawGenreCover/Assamese/"),
(11, "Balochi", "rawGenreCover/Balochi/"),
(12, "Bengali", "rawGenreCover/Bengali/"),
(13, "Bhajan", "rawGenreCover/Bhajan/"),
(14, "Bhangra", "rawGenreCover/Bhangra/"),
(15, "Bhojpuri", NULL),
(16, "Blues", "rawGenreCover/Blues/"),
(17, "Bollywood", "rawGenreCover/Bollywood/"),
(18, "Carnatic", "rawGenreCover/Carnatic/"),
(19, "Chhattisgarhi", "rawGenreCover/Chhattisgarhi/"),
(20, "Children's Music", "rawGenreCover/Children's Music/"),
(21, "Choir", "rawGenreCover/Choir/"),
(22, "Choral", "rawGenreCover/Choral/"),
(23, "Christian", "rawGenreCover/Christian/"),
(24, "Chutney", "rawGenreCover/Chutney/"),
(25, "Classical", "rawGenreCover/Classical/"),
(26, "Comedy", "rawGenreCover/Comedy/"),
(27, "Country", "rawGenreCover/Country/"),
(28, "Dance", "rawGenreCover/Dance/"),
(29, "Dancehall", NULL),
(30, "Devotional", "rawGenreCover/Sikh Devotional/"),
(31, "DJ", "rawGenreCover/DJ/"),
(32, "Dubstep", NULL),
(33, "EDM", "rawGenreCover/EDM/"),
(34, "Electronic", "rawGenreCover/Electronic/"),
(35, "English", NULL),
(36, "Fado", "rawGenreCover/Fado/"),
(37, "Film", NULL),
(38, "Flute", "rawGenreCover/Flute/"),
(39, "Folk", "rawGenreCover/Folk/"),
(40, "French", NULL),
(41, "Fusion", "rawGenreCover/Fusion/"),
(42, "German", "rawGenreCover/German/"),
(43, "Ghazal", "rawGenreCover/Ghazal/"),
(44, "Gospel", "rawGenreCover/Gospel/"),
(45, "Greek", "rawGenreCover/Greek/"),
(46, "Grime", "rawGenreCover/Grime/"),
(47, "Gujarati", "rawGenreCover/Gujarati/"),
(48, "Haryanvi", "rawGenreCover/Haryanvi/"),
(49, "Hindi", "rawGenreCover/Hindi/"),
(50, "Hindustani", "rawGenreCover/Hindustani/"),
(51, "Hip Hop", "rawGenreCover/Hip Hop/"),
(52, "House", "rawGenreCover/House/"),
(53, "Indian", "rawGenreCover/Indian/"),
(54, "Indian Classical", "rawGenreCover/Indian Classical/"),
(55, "Indie", "rawGenreCover/Indie/"),
(56, "Instrumental", "rawGenreCover/Instrumental/"),
(57, "Italian", NULL),
(58, "J-Pop", "rawGenreCover/J-Pop/"),
(59, "Jazz", "rawGenreCover/Jazz/"),
(60, "K-pop", "rawGenreCover/K-pop/"),
(61, "Kannada", NULL),
(62, "Kashmiri", "rawGenreCover/Kashmiri/"),
(63, "Kirtan", "rawGenreCover/Kirtan/"),
(64, "Konkani", NULL),
(65, "Korean", "rawGenreCover/Korean/"),
(66, "Kurdish", NULL),
(67, "Latin", "rawGenreCover/Latin/"),
(68, "Latin Trap", "rawGenreCover/Latin Trap/"),
(69, "Latvian Folk", NULL),
(70, "Malayalam", "rawGenreCover/Malayalam/"),
(71, "Manipuri", "rawGenreCover/Manipuri/"),
(72, "Marathi", "rawGenreCover/Marathi/"),
(73, "Metal", "rawGenreCover/Metal/"),
(74, "Naat", "rawGenreCover/Naat/"),
(75, "Nepali", "rawGenreCover/Nepali/"),
(76, "Odia", "rawGenreCover/Odia/"),
(77, "Pakistani", NULL),
(78, "Pashto", "rawGenreCover/Pashto/"),
(79, "Persian", "rawGenreCover/Persian/"),
(80, "Playback", NULL),
(81, "Poetry", "rawGenreCover/Poetry/"),
(82, "Politics", "rawGenreCover/Politics/"),
(83, "Pop", "rawGenreCover/Afro-Pop/"),
(84, "Portuguese", "rawGenreCover/Portuguese/"),
(85, "Producer", "rawGenreCover/Producer/"),
(86, "Punjabi", "rawGenreCover/Punjabi/"),
(87, "Qawwali", "rawGenreCover/Qawwali/"),
(88, "R&B", NULL),
(89, "Rajasthani", "rawGenreCover/Rajasthani/"),
(90, "Rap", "rawGenreCover/Rap/"),
(91, "Reggae", NULL),
(92, "Reggaeton", NULL),
(93, "Remix", "rawGenreCover/Remix/"),
(94, "Rock", "rawGenreCover/Rock/"),
(95, "Romanian", "rawGenreCover/Romanian/"),
(96, "Sanskrit", "rawGenreCover/Sanskrit/"),
(97, "Santali", NULL),
(98, "Sertanejo", NULL),
(99, "Sikh Devotional", "rawGenreCover/Sikh Devotional/"),
(100, "Sindhi", NULL),
(101, "Sinhala", "rawGenreCover/Sinhala/"),
(102, "Soul", "rawGenreCover/Soul/"),
(103, "Soundtrack", "rawGenreCover/Soundtrack/"),
(104, "Spanish", "rawGenreCover/Spanish/"),
(105, "Speech", "rawGenreCover/Speech/"),
(106, "Spiritual", "rawGenreCover/Spiritual/"),
(107, "Spoken Word", NULL),
(108, "Sufi", "rawGenreCover/Sufi/"),
(109, "Swahili", "rawGenreCover/Swahili/"),
(110, "Swedish", "rawGenreCover/Swedish/"),
(111, "Tamil", "rawGenreCover/Tamil/"),
(112, "Telugu", "rawGenreCover/Telugu/"),
(113, "Thai", "rawGenreCover/Thai/"),
(114, "Trance", "rawGenreCover/Trance/"),
(115, "Turkish", "rawGenreCover/Turkish/"),
(116, "Urban", "rawGenreCover/Urban/"),
(117, "Urdu", "rawGenreCover/Urdu/"),
(118, "Various", NULL),
(119, "Western Classical", "rawGenreCover/Western Classical/"),
(120, "World", NULL),
(121, "Babul", "rawGenreCover/Babul/");