logging:
  level:
    root: warn
    com.poulastaa: warn

grpc:
  server:
    port: ${validator-service.grpc.port:8078}
    reflection-service-enabled: true

spring:
  application:
    name: ${validator-service.name:validator}
    version: ${validator-service.version:1.0.0}

  config:
    name: ${discovery.name:discovery}
    import: optional:configserver:http://kyoku.poulastaa.shop:1200
  profiles:
    active: dev

  cloud:
    config: # --------------------------------- CONFIG-SERVER ---------------------------------
      uri: http://kyoku.poulastaa.shop:1200
      username: admin
      password: configServer101$@
      profile: dev
      label: main
      fail-fast: true

      retry:
        initial-interval: 1000
        multiplier: 1.6
        max-attempts: 4
        max-interval: 2000

      request-connect-timeout: 5000
      request-read-timeout: 5000

  output:
    ansi:
      enabled: detect

  devtools:
    livereload:
      enabled: true
      port: ${validator-service.livereload-port:8079}

jwt:
  access:
    secret: ${jwt.access.secret}
    subject: ${jwt.access.subject}
    issuer: ${jwt.access.issuer}
    audience: ${jwt.access.audience}
    claim:
      key: ${jwt.access.claim-key}
    time: ${jwt.access.time}
    unit: ${jwt.access.unit}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://kyoku.poulastaa.shop:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      grpc.port: ${validator-service.grpc.port:8078}