package com.poulastaa.kyoku.auth.model.response

enum class UserStatus {
    USER_CREATED,
    USER_FOUND,
    USER_FOUND_NO_GENRE,
    USER_FOUND_NO_B_DATE,
    USER_FOUND_NO_ARTIST,
    USER_FOUND_NO_PLAYLIST,
    USER_NOT_FOUND,
    INVALID_EMAIL,
    PASSWORD_DOES_NOT_MATCH,
    EMAIL_ALREADY_IN_USE,
    INTERNAL_SERVER_ERROR,
}