create database if not exists Kyoku;
use Kyoku;

create table if not exists Country
(
    id      int primary key auto_increment,
    country varchar(40) unique not null
);

Insert Ignore into Country (country)
values ("India"),
       ("Romania"),
       ("Netherlands"),
       ("Pakistan"),
       ("USA"),
       ("Germany"),
       ("Unknown"),
       ("Russia"),
       ("Morocco"),
       ("Puerto Rico"),
       ("Canada"),
       ("South Korea"),
       ("Australia"),
       ("France"),
       ("UAE"),
       ("UK"),
       ("Nigeria"),
       ("Bangladesh"),
       ("South Korea"),
       ("Turkey"),
       ("Germany"),
       ("United States"),
       ("United Kingdom"),
       ("Israel"),
       ("Iran"),
       ("Azerbaijan"),
       ("Czech Republic"),
       ("Sri Lanka"),
       ("Lebanon"),
       ("Colombia"),
       ("Afghanistan"),
       ("Jamaica"),
       ("Albania"),
       ("Trinidad and Tobago"),
       ("Brazil"),
       ("Nepal"),
       ("France"),
       ("Georgia"),
       ("Kenya"),
       ("Italy"),
       ("Maldives"),
       ("Egypt"),
       ("International"),
       ("United Arab Emirates"),
       ("Kazakhstan"),
       ("Mali"),
       ("Norway"),
       ("Mexico"),
       ("Sweden"),
       ("Uzbekistan"),
       ("Various"),
       ("India"),
       ("UK"),
       ("Latvia"),
       ("Armenia"),
       ("Greece"),
       ("Jordan"),
       ("Netherlands"),
       ("Tanzania"),
       ("Singapore"),
       ("Malaysia"),
       ("Syria"),
       ("Spain"),
       ("West Indies"),
       ("Portugal"),
       ("Iraq"),
       ("Belgium"),
       ("Indonesia"),
       ("Poland"),
       ("Japan"),
       ("United Kingdom"),
       ("Barbados"),
       ("South Africa"),
       ("Thailand");