Insert into album (name) values
('8 AM Metro'),
('Beast'),
('Badmaashi'),
('Bolna Tu Bantai'),
('Main Atal Hoon'),
('Crakk'),
('Modern Love Chennai'),
('Stolen Dreams'),
('Honey 3.0'),
('Fighter'),
('Ghost'),
('Teri Baaton Mein Aisa Uljha Jiya'),
('Merry Christmas'),
('Salaar'),
('Queen Of Hearts'),
('Raah'),
('Annhi Dea Mazaak Ae'),
('Raangi'),
('Maamannan'),
('Modern Love Mumbai'),
('Pathu Thala'),
('Chandramukhi 2'),
('Mr And Mrs Narula'),
('Maa'),
('White Panjab'),
('Himesh Ke Dil Se'),
('Sher Bagga'),
('Jalwa'),
('Hustle 3'),
('Chengiz'),
('Gandhi Godse Ek Yudh'),
('Rocketry'),
('Ragni 18'),
('Mandap'),
('Hustle 2.0'),
('PR'),
('Adipurush Tamil'),
('Jugjugg Jeeyo'),
('Lehmberginni'),
('Kade Dade Diyan Kade Pote Diyan'),
('D 2022'),
('Rani Haar'),
('Varisu'),
('Varisu Hindi'),
('Brahmastra'),
('Leo'),
('Jailer'),
('Vikrant Rona Hindi'),
('Macharla Chunaav Kshetra'),
('Leo Hindi'),
('Ready'),
('Rebel'),
('Recall'),
('Heropanti 2'),
('Remember'),
('Kaathuvaakula Rendu Kaadhal'),
('Any How Mitti Pao'),
('Mahaan - Tamil 2021'),
('Rise N Shine'),
('Shaakuntalam'),
('Robinhood'),
('Yutha Satham'),
('Kaali Sarhad'),
('Kulche Chole'),
('Roop Radhaa Kaa'),
('Rise Fall Rise'),
('Tiger 3'),
('Qala'),
('Rukka Dhani Me'),
('Sukoon'),
('Coffee With Kadhal'),
('Kali Jotta'),
('Love Today'),
('I Dont Care'),
('Saah'),
('Saanjh'),
('Kaari'),
('Saans 2'),
('Sultan Of Delhi'),
('Accidental Farmer'),
('Bachchhan Paandey'),
('Drishyam 2'),
('Babul'),
('Sabki Baaratein Aayi'),
('Udeekan Teriyan'),
('Sab Ton Sohna Reverb'),
('Sachi Muchi'),
('Industry 2'),
('Sadi Goodluck'),
('Safety'),
('Aaja Mexico Challiye'),
('Sirf Ek Bandaa Kaafi Hai'),
('The Great Indian Family'),
('The UK07 Rider'),
('Tu Hi Yaar Mera'),
('Sajna'),
('Godday Godday Chaa'),
('James Tamil'),
('Mere Husband Ki Shadi'),
('LGM'),
('MOH'),
('Mahi Mera Nikka Jeha'),
('3 AM Sessions'),
('Yaanai'),
('Sandal'),
('Gatta Kusthi'),
('Sang E Mah'),
('Look At Me'),
('Prithviraj'),
('Race'),
('Munda Southall Da'),
('Bumper'),
('Vajood'),
('The New Blood Bharateeyans'),
('New Life'),
('Sathya Sothanai'),
('Sathi Re'),
('Animal'),
('Kick Tamil'),
('Sat Samundar'),
('Yaariyan 2'),
('Neymar'),
('Savidhan'),
('First Of A Kind'),
('Maaveeran'),
('Addiction'),
('August 16 1947'),
('Doli Saja Ke Rakhna Bhojpuri 2022'),
('Karumegangal Kalaigindrana'),
('Ek Villain Returns'),
('Shalla'),
('D Town To B Town'),
('Shararah'),
('Khao Piyo Aish Karo'),
('Another Side'),
('Hi Papa'),
('Mastaney'),
('Masand'),
('Sher'),
('Selfiee'),
('Dhaakad'),
('Jind Mahi'),
('Shikaar'),
('Ponniyin Selvan'),
('RRR 2021'),
('Shonk'),
('IPL Anthem'),
('Tu Jhoothi Main Makkaar'),
('Bappa Shendur Laal'),
('Dakuaan Da Munda 2'),
('Maante Naahi Haar'),
('Sikhle'),
('Kadhal Conditions Apply'),
('Single Life'),
('Wolf'),
('Paramporul'),
('Hey Sinamika'),
('The Great Indian Kitchen'),
('Sitara'),
('Bakasuran'),
('Shonk Sardari Da'),
('Slayer'),
('Snakes And Ladders'),
('SOA'),
('Making Memories'),
('Main Te Bapu'),
('Amigo Garage'),
('Layers'),
('Sinam'),
('Virupaksha Tamil'),
('Road To Crore'),
('Sone Ki Tagdi'),
('Maja Ma'),
('Gumraah'),
('Sonrisa'),
('Batch 2013'),
('Sardar Tamil 2022'),
('SOTB'),
('Speechless'),
('Speed'),
('Archives'),
('Still Stuck'),
('G Thing'),
('Sugar'),
('Kgf Chapter 2 Tamil'),
('Etharkkum Thunindhavan'),
('The Archies'),
('Ittu Si Baat'),
('Satyaprem Ki Katha'),
('Cirkus'),
('Galwakdi'),
('Surma Lapete 2'),
('Surma Rukya Na'),
('Suzhal'),
('Maa Da Ladla'),
('O2'),
('System Tagda'),
('Double Xl'),
('Taare'),
('Taare Tuttange'),
('Tabahi'),
('The Great Escape'),
('Tamasha'),
('Label'),
('Multani Mitti'),
('Tareefan'),
('Dinosaurs'),
('Tauba'),
('Taur Kiwe Aa'),
('My Way Main Te Mere Geet'),
('Jannatein'),
('Kisi Ka Bhai Kisi Ki Jaan'),
('Tere Bin'),
('Tu Hovein Main Hovan'),
('Raaz'),
('Laal Singh Chaddha'),
('Indie Hain Hum 3'),
('Tere Piche'),
('Tu Jhoothi Main Makkar'),
('Kuttey'),
('Zara Hatke Zara Bachke'),
('Tere Wala Jatt'),
('Teri Aukat'),
('Teri Bhabhi Ka Phone Hai'),
('Zindagi Zindabaad'),
('Teri Yaad'),
('Thiruchitrambalam'),
('Thookudurai'),
('God Father Hindi'),
('Kaiyum Kalavum'),
('The Village'),
('Ripupbury'),
('Putham Pudhu Kaalai Vidiyaadhaa'),
('Thappad'),
('Thar'),
('Dasara Tamil'),
('Sweet Kaaram Coffee'),
('Nadhi'),
('Brahmastra Tamil'),
('Jalsa'),
('An Action Hero'),
('Parking'),
('Lal Salaam'),
('Runway 34'),
('Think Uncut'),
('Ayothi'),
('Kuttram Purinthal'),
('Thokar'),
('Sita Ramam Tamil'),
('Gargi Tamil'),
('Laththi'),
('Taanakkaran'),
('Cobra Tamil'),
('Veeran'),
('Custody'),
('Hit The First Case'),
('Tinkiya'),
('Tinna Vicho'),
('Mere Desh Ki Dharti'),
('Jeena Abhi Baaki Hain'),
('Laung Laachi 2'),
('Adiye'),
('Babe Bhangra Paunde Ne'),
('Bhaichara On The Floor'),
('Bhool Bhulaiyaa 2'),
('Carry On Jatta 3'),
('Dehati Disco'),
('Dhokhe'),
('Dil Te Dil Tak'),
('Ezhu Kadal Thaandi'),
('Farhana'),
('Gehraiyaan'),
('Indian Police Force'),
('Kabzaa Hindi'),
('Kadamaiyai Sei'),
('King Of Kotha'),
('Mister Mummy'),
('Musafir'),
('Nigah Marda Ayi Ve'),
('Nishana'),
('Sab Moh Maaya Hai'),
('Seenu Dolu'),
('Shaadi Mubarak'),
('Shamshera Hindi'),
('Shehzada'),
('Student Kota'),
('Takku Mukku Tikku Thalam'),
('Thank God'),
('Udeekan Teriyaan'),
('Vikram Hindi'),
('Yaaran Da Rutbaa'),
('Yankee'),
('Zohrajabeen'),
('Razaa E Ishq'),
('Signature'),
('Trap Clap'),
('Truck Anthem'),
('Dear Dia'),
('Bawaal'),
('Khalli Balli'),
('Freddy'),
('Tiku Weds Sheru'),
('CAT'),
('Rajini The Jailer'),
('Dhokha 2022'),
('Aashiqui Bhojpuri'),
('Tu Jo Nahi Hai Yaha'),
('Tu Meri Aashiqui'),
('Kushi'),
('Tu You'),
('Janhit Mein Jaari'),
('Toolsidas Junior'),
('Gadar 2'),
('Vinveli Devathai'),
('Understand'),
('Prithviraj Tamil'),
('Unki Aadat Si'),
('Rudhran'),
('Yeevaal'),
('U And Me'),
('Viruman'),
('Thudikkum Karangal'),
('Vair'),
('Sass Meri Ne Munda Jameya'),
('Code Name Tiranga'),
('Khichdi 2'),
('Jawan'),
('Vattam'),
('Naane Varuvean'),
('Mudhal Nee Mudivum Nee'),
('Do Baaraa'),
('Vekh Le Viah'),
('Varalaru Mukkiyam'),
('Venam Baby'),
('Vendum'),
('Fukrey 3'),
('Rocky Aur Rani Kii Prem Kahaani'),
('Khadari'),
('Jiivi 2'),
('Bimbisara'),
('Yaar Mera Titliaan Warga'),
('Liger Hindi'),
('Jind Mahi 2022'),
('Khaao Piyo Aish Karo'),
('The Last Good Album'),
('Fursat'),
('EP'),
('Whats Beef'),
('Jahaan Chaar Yaar'),
('Where Do I Go'),
('Whips And Clips'),
('Prince Tamil'),
('Who Want It'),
('Why'),
('Full Desi 2'),
('Chatrapathi'),
('Wrong Route'),
('W'),
('Yaadan 2'),
('Haterz'),
('Andhagan'),
('Yadav Brand 3'),
('Sardar'),
('Monica O My Darling'),
('Zwigato'),
('Rangoli'),
('You And Me'),
('You N I'),
('You Talking To Me'),
('Bajao'),
('Zindagi Banti Ho'),
('Zindagi Ke Rang'),
('Pathaan Tamil Version'),
('1 AM'),
('Oh Manapenne'),
('Aao Na'),
('Aao Sanam Jao Sanam (From &quot; Mere Chachu Ki Shadi&quot;)'),
('A Tribute to Jagjit Singh'),
('Aapna Koi Nahi'),
('Aap Khas Ho'),
('O Sanam (Greatest Hits : Lucky Ali)'),
('Aara'),
('Aara Piya'),
('Aarti Sangrah'),
('Aarti Vol 3'),
('Laxmi Aarti'),
('Enna Solla Pogirai'),
('Aashiquii Kaa Gum'),
('Radhe Shyam - Hindi'),
('Aashiq Mud Na Jaawe'),
('Aas - Dil Da Ki Banuga'),
('Pistha'),
('Mookuthi Amman'),
('Aatishbaazi'),
('Aatmvishvas'),
('Aawara Shaam Hai'),
('Aawazein'),
('Aaya Jado Da'),
('Aaya Jado Da x Dholla'),
('Bharat'),
('Time To Dance'),
('Puaada'),
('Bhoot Police'),
('Aazmaa Le Ishq Mera'),
('My Dear Bootham'),
('Mubarak Ho Bali Hua Hai'),
('Above All'),
('Ab Aaja'),
('Parwane'),
('Holiya Mein'),
('Ab Ke Sawan'),
('Ab Kya Jaan Legi Meri'),
('Ab Nahi Hogi Mulakate'),
('Ab Nahi'),
('Hacked'),
('Ab Tere Bina'),
('Bhoomi'),
('Achha Ve Achha'),
('Rambo'),
('Naanga Romba Busy'),
('Adab Jatt'),
('Ada Pind '),
('Adha Jisam'),
('Adha Pind 2'),
('Adha Shehar'),
('Navarasa'),
('Sarbath'),
('Adhoora Hoon'),
('Adhoori Kahaani'),
('Adhura'),
('Adipoli'),
('Bachelor'),
('Writer'),
('Adi Penne'),
('Aelay (Original Motion Picture Soundtrack)'),
('Tadap'),
('Haathi Mere Saathi'),
('Ae Hay'),
('Ae Jaan Bhaag Chala Ho'),
('Ae Mere Des'),
('Ae Mere Dil'),
('Ae Raja Badaniya Tutata'),
('Ae Sanamm'),
('Shikara'),
('Ae Watan'),
('Afeem'),
('Affair'),
('Afghani Tadka'),
('Dil Bechara'),
('Afsos Karoge'),
('After Party'),
('After You'),
('HIDDEN GEMS'),
('Agarr tumm naa hote'),
('Age 19'),
('Age'),
('Agg Att Koka Kehar'),
('Aghori'),
('Ahiran Ke Saman'),
('Ailaan'),
('Sooryavanshi'),
('Malaal'),
('Kalank'),
('Malum Hai Na'),
('Aise Hue Tere Bin'),
('Aise Kiu'),
('Aise Na Chhoro'),
('Blessed'),
('The Main Man'),
('Aish Karengi'),
('Shubh Mangal Zyada Saavdhan'),
('The Power of Dreams of a Kid'),
('Jai Mummy Di'),
('Ajeeb Dastan (Cover Version)'),
('Ajib Dastaan'),
('crowned head'),
('Kesari'),
('Ajnabi'),
('Snitches Get Stitches'),
('Akda Di Patti'),
('Teeja Punjab'),
('Akhaa Vich'),
('Akhan Di Laali'),
('Akhan Neeliya (feat. Rav-E Sandhu)'),
('Wishlist'),
('Akhan Sujjiyan'),
('Mere Yaar'),
('Commando 3'),
('Tuesdays And Fridays'),
('Akhiyan Di Gal'),
('Shiddat'),
('Underrated'),
('Akh Da Dang'),
('Akh Radar'),
('Say My Name'),
('Akke Firde'),
('AK 47'),
('Aladdin'),
('Koogle Kuttappa'),
('8 Chances'),
('Alcohol'),
('Gangaajal'),
('Blank'),
('Ali Baba'),
('Romeo Akbar Walter - RAW'),
('Allah Maaf Kare'),
('Allah Meharbaan'),
('Allah Ve'),
('Alli Pookal'),
('Rano'),
('All Bamb'),
('All Lies'),
('All White Nakhro'),
('Alone'),
('Alvida'),
('Always For You'),
('Aly'),
('Durga Chalisa'),
('Ambran De Chann Warga'),
('Tadipaar'),
('Shiva Shivaa Win Aattam Aarambam'),
('Mookuthi Amman (Original Background Score)'),
('Amma Jaye'),
('Sufna'),
('Am Just Thinking'),
('Anakh'),
('Jango'),
('Anandan Wali Puri'),
('Annabelle Sethupathi'),
('Mumbai Diaries (Music from the Original Web Series)'),
('Toofaan'),
('Sher Singh'),
('Andata'),
('Master'),
('And Band Bole Chora'),
('I'),
('Angelina'),
('Chak De Fatte 2021'),
('Angry Nature'),
('Anjaan'),
('Sanak'),
('Ankhiyaan Da Ghar'),
('Pati Patni Aur Woh'),
('Annaatthe Annaatthe (From &quot;annaatthe&quot;)'),
('Paris Paris'),
('Udanpirappe (Original Motion Picture Soundtrack)'),
('Antidote'),
('Anyone'),
('Apart'),
('Apna Banauna'),
('Apna Jahaan'),
('Nothing Like Before'),
('Gully Boy'),
('APNA VIAH'),
('Apne'),
('Apni Piwa'),
('Apni To Jaise Taise'),
('Fuffad Ji'),
('Approch'),
('Apsraa'),
('Anbarivu'),
('Arcade'),
('Area Ch Kath'),
('Are You Okay'),
('Are You Ready for the Big Bang'),
('Hridayam'),
('Baaraat'),
('Kombu Vatcha Singamda'),
('Armani'),
('Arrogance vs. Attitude'),
('Arthi'),
('Durga Stuti'),
('Asal Mein - Single'),
('Ashiqui'),
('Happy Hardy And Heer'),
('Ashke Ashke'),
('Holiday - A Soldier Is Never Off Duty'),
('Asin Pindan Alley'),
('Asku Maaro'),
('Asla'),
('Asla Once Again'),
('Asla Vs Masla'),
('Asla vs Suit'),
('Asli Gernator'),
('Gunjan Saxena'),
('Asool'),
('Aso Ke Holi'),
('Astronaut - Aide-Memoire'),
('AS-SALAM WALEKUM'),
('Athra Style (From&quot;Yes I Am Student&quot;)'),
('Attaboy'),
('Attachment'),
('Attitude American'),
('Attitude'),
('Attitude (feat. Fateh &amp; Inderpal Moga)'),
('Chandigarh Kare Aashiqui'),
('Att Da Shikari'),
('Att'),
('Att Look'),
('My Turn'),
('Badla'),
('Aukaat'),
('Aunde Rahe'),
('Aundi Kudiye'),
('Kya Meri Sonam Gupta Bewafa Hai'),
('Aur Kuch Nahi'),
('Main Prem Ki Diwani Hoon'),
('Aur Pyaar Karna Hai'),
('Love Aaj Kal'),
('Awaara 2020'),
('Awaara Bhanware - Dhrriti Saharan'),
('Dilli Kaand'),
('Awaaz'),
('Dabangg 3'),
('Aashiq, Vol. 1'),
('Aya Ladiye'),
('Aye Didi Jija Ji'),
('Aye Hai'),
('Aye Mere Dil'),
('Babloo Bachelor'),
('Azaan'),
('Aziyat'),
('Baadlon Se Aage'),
('Baahan Teriyan'),
('Baahon Mein'),
('Baaje'),
('Baaju Band'),
('Baaki Sab Theek Hai'),
('Baalma Dandiya Anthem'),
('Baapu'),
('Baapu (Tunka Tunka)'),
('Yes I Am Student'),
('Insaaf'),
('Baarishein'),
('Baarish Ban Jaana'),
('Baarish Ki Jaaye'),
('Unwind'),
('Baarish'),
('Baari Barsi'),
('Baari'),
('Tehreek'),
('Baatan Puadh Kiyan'),
('Baawla'),
('Baazi Sava Lakh Di'),
('Baazi'),
('Baba 4'),
('Baba Ji'),
('Babbu Maan De Chele'),
('Babuni Tere Rang Mein'),
('Babuni Trend Kar Rahi Ho'),
('Babu Aao Na'),
('Baby Bewafa'),
('Baby'),
('Bachava (Save Her)'),
('Bachcha Party'),
('Bachdiyan Naa'),
('Bacheyan Di Maa'),
('Bachpan Ka Pyaar'),
('Bachpan Ki Yaari'),
('Bach Goriye'),
('Bach Ke Rehna (Red Notice)'),
('Back End'),
('Back Pe Attack'),
('Back to Start'),
('Badama Wali Kheer'),
('Badami Rang'),
('Badami'),
('Badan Pe Sitare Ft. Asim Riaz And Sehnoor'),
('Bad&#039;dua (Original Score)'),
('Badi Asaani Se'),
('Tips Rewind A Tribute To Jagjit Singh'),
('Housefull 4'),
('Badle'),
('Badmashi (feat. Gurlez Akhtar)'),
('Badmashi'),
('The Future'),
('Badmash 2'),
('Badma'),
('Badnaam'),
('Badnamiyan'),
('Badnam Gabru'),
('Ha Kar De Meri Moto'),
('Singga Bolda Veere'),
('Badnam Rahn De'),
('Badshah'),
('Bad boys (feat. Inderpal Moga)'),
('Suraj Pe Mangal Bhari'),
('Bad Boy'),
('Bad Boy Life'),
('Bad Boy X Bad Girl'),
('Bad Circumstance'),
('Bad Habits'),
('Bad Job'),
('Bad Munda'),
('Bad Name'),
('Bad Thought'),
('Bagad - Single'),
('Bagalwali'),
('Bagawat'),
('Bagdo Nachi Samman Me (feat. Sapna Chaudhary &amp; Kay D)'),
('Bagdo'),
('Bagheera'),
('Bagli Me Jahar Layenge'),
('Bahana'),
('Bahane'),
('Yaad (A Name To Remember)'),
('Bahla Changa'),
('Bahot Roye'),
('Sivakumarin Sabadham'),
('Sandwich 2006'),
('Bahu Nachi Kilki Pati'),
('Bahu Nai Naveli'),
('Bahu Pataka'),
('Bahu Set Falane Ki'),
('Bahu Ya Chala - Single'),
('Baila Conmigo'),
('Kaagaz'),
('Ramaiya Vastavaiya'),
('Baithe Baithe'),
('Baithoon Nayee Balero Main'),
('Bai Bai'),
('Next Chapter'),
('Bajo'),
('Bajre Da Sitta'),
('Cash'),
('Balam Gud Gudiya Barata'),
('Balam Ka System'),
('Balam Mera Atyachari'),
('Balam Mera'),
('Balayein'),
('Balcony'),
('Jersey'),
('Addi Tappa'),
('Balle Balle'),
('Balle'),
('Bal Gopala'),
('Laxmii'),
('Bambiha Bole'),
('Bamb Grenade'),
('Banadi'),
('Monsoon with DIVINE'),
('Banda Maar Du'),
('Banda Maar'),
('Bandeh'),
('Sardar Ka Grandson'),
('Bandeya'),
('Guns of Banaras'),
('Bande Khani'),
('Bande Thik Ni'),
('Jawaani Jaaneman'),
('Bandook'),
('Bandook Bole Se'),
('Helmet'),
('Bangliniya'),
('Banglo'),
('Bangroo'),
('Bang'),
('Banjaran'),
('Banjara'),
('Banke Chale Morni'),
('Banke Tu Baarish'),
('Ganga Ki Kasam'),
('Banna Re'),
('Dhindora'),
('The Blood'),
('Bhavai'),
('Hum Do Humare Do'),
('Bantai Ki Public'),
('Ban Pindan Aale'),
('Ban Than Dole'),
('Bapu'),
('Bapu Bamb Banda'),
('Bottles &amp; Guns'),
('Quarantine In Punjab'),
('Bapu Tere Karke'),
('Baraat'),
('Durgamati - The Myth'),
('Squad'),
('Humshakals'),
('Barbaad'),
('Barbie Doll'),
('Bareli'),
('Barish'),
('Barood'),
('Jagame Thandhiram 2021'),
('Barsaat'),
('Judaiyaan'),
('Barsaat Ki Dhun'),
('Barsi'),
('Ved'),
('Super 30'),
('Basanti'),
('Bas Ek Tera Main Hoke'),
('Bas Kar Bas Kar'),
('Bas Kar Pagli'),
('Bas Terre Ho Gaye'),
('Batch Wali Chhori - Single'),
('Bateu'),
('Batista Bomb'),
('Motichoor Chaknachoor'),
('Navjeeta'),
('Batua'),
('Bawli Hori Se'),
('Bawra Man'),
('Bazaar'),
('Ba Khuda'),
('Beat Do'),
('Virgin Bhanupriya'),
('Beautiful'),
('Beauty Parlour'),
('Bebe Bapu'),
('Beby Farebee'),
('Bechain Jawani'),
('Delhi Belly'),
('Bedardi Se Pyaar Ka'),
('Beedi'),
('Beef'),
('Befikar Raho'),
('Befikra (feat. Kamzinkzone)'),
('Begane Chehre'),
('Begane Putt'),
('Begum'),
('Behaal'),
('Behad'),
('Behind Barz'),
('Bole Naina - Silences Speak'),
('Darbaan'),
('Bekaar'),
('Kabir Singh'),
('Belafz Baatein'),
('Beliyaa'),
('Beliya'),
('Bell Bottom'),
('Bepanah'),
('Bepanah Ishq'),
('Bepanah Pyaar'),
('Bepannah 2.0 (Sad Version)'),
('Beparwah'),
('Beparwaiyaan'),
('Beparwaiyan'),
('Pagglait'),
('Berozgaari Ke Saar Bhail Ba'),
('Berukhi (Original Score)'),
('Mr. Nair'),
('Besharam Bewaffa'),
('Besharam Jana Bewafa'),
('Besharam Si Nazrein'),
('Besharmi'),
('Best Of 2021 Mashup (End Year 2021 Mashup) (feat. DJ DALAL London)'),
('Betiyaan Pride Of Nation'),
('Better Half'),
('Nobody Is Listening'),
('Bewafaiyan'),
('Bewafai Ke Award Leke Ja'),
('Bewafai'),
('Bewafao Se Savdhan'),
('Bewafayi'),
('Bewafa 2'),
('Bewafa Ae Dil'),
('Bewafa'),
('Bewafa Saheli'),
('Bewafa Tera Masoom Chehra'),
('Bewafa Tera Muskurana'),
('Beydil'),
('Street Dancer 3D'),
('Be Intehaan Sa'),
('Be Mine'),
('Be Ready'),
('Bhaag Thande'),
('Bhabhiye'),
('Bhabhi Bhabhi'),
('Bhabhi Sang Devar'),
('Mela'),
('Bhabi'),
('Radak (The First Chapter)'),
('Bhabi x2'),
('Bhagat'),
('Bhaga Aala'),
('Bhaiya Rangle Naya Saari'),
('Bhuj The Pride Of India'),
('Bhai Bhai'),
('Antim - The Final Truth'),
('Bhala Kare Bhagwan'),
('Bhammariyo'),
('Bhangre Paine Hi Paine'),
('Baaghi 3'),
('Bharosa'),
('Bhartar 2'),
('Bhartar'),
('Bhatar Aiba Ki Na'),
('Bhatar Mange Puppy'),
('Bhatar Sanghe DP'),
('Bhatar Tohar Rowat Hoi'),
('Bhauji Khola Na Kewadi'),
('Bhauji Ko Rang Na Lagana Hai'),
('Roohi (Original Motion Picture Soundtrack)'),
('Amavas'),
('Khandaani Shafakhana'),
('Bheegi Bheegi'),
('Bheeg Jaunga'),
('Bhen Teri'),
('Bhitar Ke Titar - Single'),
('Bholenath Ki Shaadi'),
('Bhole Di Baraat, Pt. 2'),
('Bhole'),
('Bhole Shankar'),
('Bhuaa'),
('Bhula Diya - Single'),
('Bhula Dunga'),
('Bhula Na Teri Baatein'),
('Bhulekha Maan Da'),
('Bhulekha'),
('Bhule Nahin Hain Hum'),
('Bhull Jaan Waaleya'),
('Yaarian Dildariyan'),
('Biana'),
('Panga'),
('Bibi Bamb Returns'),
('Bicchua'),
('Bichola'),
('83'),
('Bigad Geya (feat. Gaurav Zone)'),
('My Game'),
('Big Boss'),
('Big Day'),
('Big Life'),
('Big Mad'),
('Bijlee Bijlee'),
('Bijli'),
('Bijli Ki Taar'),
('Bikhrahoon'),
('Bille Bille Nain'),
('Billi Billi Aankh'),
('Billos Town'),
('Billouri Akhiyan'),
('Billo Tu Agg'),
('Bill Tere Paarh Dite'),
('Bimariyan'),
('Bin Bole Baby Tu'),
('Bin Bulaye'),
('Bin Tere Bhi Rehlenge'),
('XL'),
('Biraj Mein Holi Khele Nandlal'),
('Birthday Boy'),
('Jugni 2021'),
('Birthday'),
('Birthday Pawri'),
('Birthday Yaaran Nal'),
('Bismillah 2'),
('Moosetape'),
('Blackia'),
('Black Coffin'),
('Black Heart (From &quot;Retake&quot;)'),
('Black Jays'),
('Black Karda'),
('Black Life'),
('Black Munde'),
('Black Pranda'),
('Black Sheep'),
('Black &amp; White'),
('Blame Game'),
('The Gorilla Bounce'),
('Blessings of Brother'),
('Blessings of Sister'),
('Bless'),
('Block'),
('Blood'),
('Blouse Ke Batan - Lagan Special'),
('Bodha Devadha'),
('Bodyguard'),
('Boht Tej'),
('Kala Shah Kala'),
('Boliyan Da Mashup'),
('Boli Jaan De'),
('Boli Te Boli'),
('Bollywood Wala Dance'),
('Bolna Pea 2'),
('Bolo hau'),
('Bol Kaffara Kya Hoga - Dj Chetas'),
('Bol Waheguru'),
('Bombay Nu Baraat'),
('Raja'),
('Down To Earth'),
('Bomb Bomb'),
('Bomb Parmanu'),
('Bona Bateu - Single'),
('7 Kadam'),
('Bonito Billo'),
('Booha'),
('Boom Boom'),
('Boost Up'),
('Booty Shake'),
('Trendsetter'),
('Bore Alone'),
('Borla'),
('Borla Chandi Ka'),
('Born 84'),
('Born Brave'),
('Bossman (feat. Dr. Kush)'),
('Botal'),
('Bounce Back'),
('Boutique'),
('Bp High'),
('Braat'),
('Brand'),
('Breaking the Rules'),
('Break Free'),
('Break Out'),
('Broken Heart'),
('Broken'),
('Brown Eye'),
('Brown Munde'),
('Bro Oye'),
('Bubble Gum'),
('Buddhi Nu Matke'),
('Gulabo Sitabo'),
('Buhe Bariyan'),
('Built in Pain'),
('Hum Bhi Akele Tum Bhi Akele'),
('Bulla Ki Jaana Mein Kaun'),
('Bulletava Pa'),
('Bullet'),
('Bullet Proof'),
('Bulleya'),
('Notebook'),
('Bungla'),
('Bunty Aur Babli 2'),
('Burj Khalifa'),
('Butta Bomma'),
('Butterfly'),
('Butterfly Wale (feat. Deepti Sadhwani)'),
('Butter'),
('But Why'),
('Byaah'),
('Byah - Single'),
('Byah Ka Ladoo'),
('By Chance'),
('By God'),
('By Myself'),
('B-Town'),
('Cadillac'),
('Call History'),
('Call'),
('Call Waiting'),
('Canada'),
('Canada Wale'),
('Canadian Boliyan'),
('Candle Light'),
('Candyman'),
('Carbon Copy'),
('Care'),
('Care Na Kare'),
('Chhalaang'),
('Carrera'),
('Carried Away'),
('Carrom Ki Rani'),
('Car Jatt Di'),
('Car Shookdi'),
('Casanova'),
('Casa Bella'),
('Cash Flow (feat. Loco Grim)'),
('Casino'),
('SK Is the Future'),
('Chaabi Gaddi Di'),
('CHAAH'),
('Chaal Kasuti S - Single'),
('Chaand Baaliyan'),
('Chaap Tilak'),
('Chaar Chudiyaan'),
('Chaar Dina Da Mela'),
('Chaar Sahibzaade'),
('Chaa Laazmi'),
('Chachi Ke Baachi Sapanwa Me Aati Hai'),
('Chadhte Laganiyan Ae Jaan'),
('Chad Gaila Stage Pe'),
('Chah Da Rang'),
('Chain Sone Ki'),
('Galatta Kalyaanam'),
('Atrangi Re'),
('Chak Begani'),
('De De Pyaar De'),
('Chale Aao'),
('Chale Aatein Hai'),
('CHALE BHI JAO'),
('Chali Chali (From &quot;Thalaivi&quot;)'),
('Thalaivii'),
('Chali Kabhi'),
('Challa'),
('Challenger'),
('Challenge'),
('Chall Balliyae'),
('Chal Dowe'),
('Ringtone'),
('Chal Geya Smaan'),
('Chal Koi Na (Let it go)'),
('Sadak 2'),
('Chamakelu Notiya Carrency Niyar'),
('Chamak Challo'),
('Chamak Chundadi'),
('Chamak Dhoop Ki - Single'),
('Chamber'),
('Chamche'),
('Chamkaur To 84'),
('Chamkila'),
('evermore (deluxe version)'),
('Champion'),
('Champ'),
('Chandani Bargi'),
('Hello Charlie'),
('Aadhaar'),
('Chanda Jhaanke'),
('Chandigarh Gye Jatt'),
('Chandigarh Jheel'),
('Virsa Bolda 2021'),
('Good Newwz'),
('Chandigarh Parhda'),
('Chandigarh Sold Out'),
('Chandi Di Dabbi'),
('Chandrashekhar'),
('Chandrawal'),
('Chandro'),
('Chand Chand'),
('Chand'),
('Chanel Mehak Da'),
('Honsla Rakh'),
('Changa'),
('Changey Mundey'),
('Change ho Gayi'),
('Changi Ni Kiti'),
('Channa'),
('Channa Veh Channa'),
('Bhoot - Part One: The Haunted Ship'),
('Ucha Pind'),
('Chann Chann'),
('Chann Ji Taras Kareo'),
('Chann Kithan'),
('Chann Mahiya Ve'),
('Chann Te Daag'),
('Chan Chan - Single'),
('Chan Vekhya'),
('Chan Ve'),
('Chaos'),
('Charcha'),
('Charche'),
('Ik Sandhu Hunda Si'),
('Chardikala'),
('Charged Up'),
('Medicine At Midnight'),
('Chaske Tere'),
('Chatak Chalungi Main Matak Chalungi'),
('Chatak Matak'),
('Chatata Telchata'),
('Dil Hi To Hai'),
('Chaudhary'),
('Cheater Boy'),
('Checkmate'),
('Chehre 2021'),
('Chehre'),
('Doctor'),
('Chemicals'),
('Chhaap Tilak'),
('The Girl On The Train'),
('Chhapaak'),
('CHHATHI MAIYA BULAYE'),
('Chhel Chhabeli'),
('Chhitte'),
('Chhora Chhori Club Mein'),
('Chhora Dhoti Aala'),
('Chhora Fauj Mai'),
('Chhor Denge (Feat. Nora Fatehi)'),
('Chhoti Tohara Choti Se Chot Lagata'),
('Chhot Pichkari'),
('Holi Dhamaka 2021'),
('Chhuta Hain Dil'),
('Chidiya Da Chamba'),
('Chidiya'),
('Chidi Chidi (From &quot;Madam Chief Minister&quot;)'),
('Chidi Udd Kaa Udd'),
('Chief Guest'),
('Chill Mode On'),
('Chill Mode'),
('Chimta Bolda'),
('Chinta Na Kar (From &quot;Hungama 2&quot;)'),
('Chithiyaan'),
('Chithi'),
('Chitiyan Kalayian'),
('Chiti Kheshi'),
('Level Up'),
('Chitte Baane'),
('Chitthi'),
('Chittiyan Kalaiyan'),
('Chit Badli Khiya Ke'),
('Chobara'),
('Chobbar'),
('Chocolate (From &quot;Sangeetkaar&quot;)'),
('Chocolate'),
('Ragasur'),
('Choodiyan - Single'),
('Choom Lun'),
('Choorha'),
('Chora Gaam Ka'),
('Chori Baliye'),
('Chori Chori'),
('Chota Number'),
('Chote Sahibzaade'),
('Chote Sahibzade'),
('Krishna Bhajan - Choti Choti Gaiya'),
('Choti Choti Gallan'),
('Mimi'),
('Ikko - Mikke'),
('Chubare Wali Baari'),
('Chubhti Hai Saansein'),
('Chudiyan'),
('Chumma 4 Go'),
('Chumma Deb Aitwar Ke'),
('Naya Saal Me Chumma Le La'),
('Chumma Rap Song'),
('Chunari Jhalkaua - Ritesh Pandey'),
('Chunar Choli'),
('Chundadi'),
('Chundad'),
('Chunni'),
('Chunriya - Single'),
('Chup Chup Milna - Single'),
('Chup Na Raho'),
('Chup'),
('Churaya'),
('Chura Ke Dil Mera (From &quot;Hungama 2&quot;)'),
('Chura Liya Hai Tumne'),
('Chura Liya'),
('Churey Wali'),
('Churi'),
('Chu Gon Do'),
('Circle'),
('Clara My Name Is Clara (From &quot;Laabam&quot;)'),
('Classmate'),
('Classy Jatt'),
('Classy Profile'),
('Clock'),
('Solace'),
('Coat Caaran Ghore'),
('Luka Chuppi'),
('Cocktail'),
('Coco'),
('Coco Cola'),
('Coffee'),
('Funzoa Songs, Vol. 11'),
('Cold Blood'),
('Colgate'),
('College Ki Chhori'),
('Collgate'),
('Come My Way'),
('Conflict'),
('Confused'),
('Confused Jatt'),
('Chhichhore'),
('Controversy'),
('Convince'),
('Cooldown'),
('Coolie No. 1'),
('Cooper'),
('Copyright'),
('Cop Cop'),
('Courage Not Loose'),
('Cover Me In Sunshine'),
('Crazy'),
('Arjun Patiala'),
('Crazy Lady'),
('Crazy Life 2'),
('Cream'),
('Crew'),
('CRIB'),
('Cricket Khidaiye'),
('Crime'),
('Criminal Crush'),
('Criminal Munda'),
('Criminal Yaar'),
('Cross Parcha'),
('Crowd'),
('Crush'),
('Corona Kumar'),
('Curfew'),
('Current'),
('Cutie Pie'),
('C Maan Gaya'),
('Daade Ki Gun'),
('Daag'),
('Daaka'),
('Daaku'),
('Daang'),
('Daang Khadke'),
('Daante Katab'),
('Daaru 24X7'),
('Daaru Aali Jidd - Single'),
('Daaru Band'),
('Daaru Da Sahaara'),
('Daaru Ki Peti'),
('Daaru Peeno'),
('Daaru Pee Ke'),
('Why Cheat India'),
('Daastan'),
('Dabbang'),
('Dabda Ni'),
('Dabde Ni'),
('Dabya Ni Karde'),
('Dada Ravan'),
('Dadi Ji De Lal'),
('Dad Da Jawai'),
('Daffa Ho'),
('Dagaa'),
('Dakait'),
('Dakke Firde'),
('Damad'),
('Daman Aali Jhol'),
('Dance Like'),
('Dance Meri Rani'),
('Velan'),
('Dangerous Eyes'),
('Dangerous'),
('Danger Life'),
('Danka Baja (From &quot;Mumbai Saga&quot;)'),
('Daraar'),
('Darani Jithani 2'),
('Dardi Aa'),
('Dard Kitna Hai'),
('Dard Tere'),
('Dard Viah Da'),
('Dark Nights'),
('Darling'),
('Darmi Cool - Single'),
('Darr Ke Aage Jeet Hai - Sukhwinder Singh'),
('Daru De Record'),
('Daru Hor Piyade'),
('Daru Vs Me'),
('Dashboard'),
('Dass Jatta'),
('Dastaan E Ishq'),
('Dastan'),
('Das Kon'),
('Date Kar Le'),
('Dawood'),
('Dayger'),
('Day Ones'),
('Dd1'),
('Dead Body'),
('Dead Roads'),
('Deaf &#039;n&#039; Dumb'),
('Deal'),
('Dear Mama'),
('December'),
('Deception'),
('Dedh Inch'),
('Dedicate For Love'),
('Saregama Bare'),
('Deewana Humke Bana Gail'),
('Deewane'),
('Deewangi Ki Raat'),
('Degree Wale Yaar'),
('Seven Rivers'),
('Deho Sajan Aaseesareeaa'),
('Dekha Gaari Mat Da'),
('Dekha Hai Jabse Tujhe '),
('Dekhe Saare Khwaab'),
('Delhi Sheher'),
('Delhi Waaliye'),
('Delhi Wali Dil Leke Bhagal'),
('Demanda'),
('Demand Saukan Ki'),
('Demand'),
('Demon'),
('Deo Asees Nanak'),
('Depend'),
('Dera Daang Te'),
('Desiyan'),
('Desi Banda'),
('Desi Bill Gate - Single'),
('Desi Chora'),
('Desi Haan Ji'),
('Desi Katta'),
('Des Malwa'),
('Devare Ke Pichkari Best Ba'),
('Devdas'),
('Deve Na Jawab'),
('Devra Gaal Misi Misi - Single'),
('Dewar ji Aah Dewar ji'),
('De Daroo'),
('De Ijaazat'),
('De Una Vez'),
('Dhadak Dhadak'),
('Dhadkan'),
('Dhake Suti Le Teddy Bear'),
('Dhakka'),
('Dhakka Laga Bukka From Tandav'),
('Dhalde Suraj'),
('Dhamaka Hoi Aara Mein'),
('Dhanwaad'),
('Dhanyawad'),
('Daadi Ji 2'),
('Dhan Dhua Ho Jai'),
('Dharala Prabhu'),
('Dhaun Cho Killa'),
('Dheeme Dheeme'),
('Dheeyan (The Pride of Father)'),
('Dhila Jurha'),
('Dhillu Ka Byah 1990'),
('Dhodiya'),
('Dhoghad - Single'),
('Dhokebaaz'),
('Dhokha'),
('Dhokha (feat. Amar Singh Chamkila &amp; Amarjot)'),
('Dhokhebaaz Ho Gaya'),
('Dhokhe Baaz'),
('Dhola Suit'),
('Dhola Ve'),
('Dholida Dhol Re'),
('Dholna'),
('Top 3 OF Gulzaar Chhaniwala'),
('Dhoondein Sitaare'),
('Jabariya Jodi'),
('Dhoor Pendi'),
('Dhuaan Dhuaan'),
('Dhua Dhua'),
('Dhund Di Khushboo'),
('Dhup'),
('Dhyan De'),
('Dial 100'),
('Diamond Ka Borla'),
('Diamond Ka Haar'),
('Diamond Ring'),
('Didi Ke Devar Jas Chahi Laika'),
('Diet'),
('Different'),
('Different Rule'),
('Dilaan De Rajya'),
('Dilaan Utte Raaj'),
('Dilbar'),
('Shubh Vivah'),
('Dildari'),
('Dilliwaliye'),
('Dilli Kasuti'),
('Dilwale'),
('Dilwe Nikal Li'),
('Dil Ali Baat'),
('Dil Badnaam'),
('Dil Beimaan'),
('Dil Chahte Ho'),
('Dil Ch Bhuchaal'),
('En Route'),
('Radhe - Your Most Wanted Bhai'),
('Dil De Naal'),
('Myrah'),
('Dil Di Gal'),
('Dil Di Queen'),
('Dil Di Rani'),
('Dil Do Kisi Ek Ko'),
('Dil Galti Kar Baitha Hai (Feat. Mouni Roy)'),
('Dil Ghayal Kare Ankhiya Ke Kajrava'),
('Dil Haare'),
('Dil Hai Deewana'),
('Ludo'),
('Dil Kare Chori'),
('Dream Girl'),
('Dil Ka Thikana'),
('Dil Ke Kagaz Pe'),
('Dil Khol Do'),
('Dil Kisi Se'),
('Dil Ki Aadat'),
('Dil Ko Karaar Aaya (Reprise)'),
('Dil Ko Karaar Aaya (From &quot;Sukoon&quot;)'),
('Dil Ko Maine Di Kasam'),
('Dil Ko Mere'),
('Dil Kya Kahe'),
('Universally SANAM'),
('Dil Lai La'),
('Dil Lauta Do'),
('Achanak'),
('Dil Lutgayi'),
('Dil Mai Basaya'),
('Dil Mangdi'),
('Dil Mein Jigar Main'),
('Mission Mangal'),
('Dil Melt Karda (From &quot;Haseen Dillruba&quot;)'),
('Dil Mera Blast - Single'),
('Dil Mera'),
('Dil Na Dukha'),
('Dil Na Lagaiti Harjayi Se'),
('Dil Na Todunga'),
('Dil Na Tod Dai'),
('Dil Ne'),
('Dil Nu Dildaar'),
('Dil Sada'),
('Dil Sambh Lai'),
('Dil Sohniye'),
('Dil Ta Bacha Eh '),
('Dil Tera Deja'),
('Indoo Ki Jawani'),
('Dil Tera V Darda'),
('Dil Tere Bina'),
('Dil Tere Bin'),
('Dil Tere Nu'),
('Dil Tere Ute Agya'),
('Dil Todna'),
('Dil Todne Se Pehle'),
('Dil Todta'),
('Adhi Tape'),
('Dil Tod Ke'),
('Dil Tudwa Ke'),
('Dil Tune Toda Hai'),
('Dil vs Watt'),
('DIL WAPIS KARDO'),
('Dil Yaar Da'),
('Kurup'),
('Kurup - Hindi'),
('Mirzapur'),
('Disco Balma'),
('Punya Paap'),
('Dishonest'),
('Distance - Aide-Memoire'),
('Distance Love'),
('Disturb'),
('Diva'),
('Diwali 2'),
('Diwana Tera'),
('Dj Aale Babu'),
('DJ Bajwadungi 2'),
('DJ Bajwadungi 3'),
('DJ Na Rok Die'),
('Dj Pe Nachungi'),
('DJ Remix Love Sayari Boom'),
('DJ Remix Love Shayari Oye Oye'),
('DJ Remix Sad Shayari Bumper'),
('Dj Wala Gaana'),
('DNA Mein Dance'),
('Dobara Alvida (From &quot;Dobara Alvida&quot;)'),
('Dogar'),
('Dole Laadle'),
('Doli Me Na Baithinhe'),
('Dollaran De Bag'),
('Dont Ask'),
('Dont Be the One'),
('Dont Care'),
('Don&#039;t Know Why'),
('Dont Like'),
('Don&#039;t Trust'),
('Don'),
('Doob Gaye'),
('Dooja Pyaar'),
('Dooriyan'),
('Door Hoke Bhi Tu'),
('Door Ho Gaya'),
('Door Thara Gaam'),
('Doremon'),
('Dosti (From &quot;RRR&quot;)'),
('Double Barrel'),
('Doun Dilan'),
('Downfall'),
('Do Din Ki Zindagi'),
('Do Gallan'),
('Do Ghoont'),
('Safar'),
('Do Nain'),
('Do Tarfa'),
('Do Vaari Jatt'),
('Choo Mandhira Kaali'),
('Dreams Come True'),
('Dream Mein Entry'),
('Still Here'),
('Dream'),
('Dress'),
('Drip Too Hard'),
('Driver Truck Ke'),
('Droptop'),
('Drunken Jatt'),
('Drunk n High'),
('Duaa Mein Yaad Rakhhna'),
('Dua Kijiye'),
('Dua'),
('Dubai vs. Canada'),
('Dudh Rangiye'),
('Duffer'),
('Dugo Rakhale Bani'),
('DUI Rupya'),
('Dujja Cup'),
('Dukh'),
('Dukh Sukh'),
('Dukki Tikki'),
('Dularuwa Jija Ji'),
('Duldi Sharab'),
('Dulhan Bani Mai Apni Piya Ki'),
('Dullah'),
('Dumdaar'),
('Hum Do Humare Do 2021'),
('Dum Laga Ke Bum Hila'),
('Duniadaari'),
('Duniadari'),
('Duniya Chhor Doon'),
('Duniya Sari'),
('Khaali Peeli'),
('Dupatta Katal Kare'),
('Durango'),
('RejctX 2'),
('Each Other'),
('East Side Flow'),
('Vaanam Kottattum'),
('Echoing'),
('Echo (with KSHMR)'),
('Naai Sekar'),
('Seethayanam'),
('Murungakkai Chips'),
('Eeswaran'),
('Radhe Shyam'),
('Ego'),
('Ehi Khaatir Aara Aile'),
('Ehsaas'),
('Eh Ke Maye Ho Gaya'),
('EightCylinder'),
('Ek Bewafaa'),
('Ek Din'),
('Ek Dua'),
('Ek Husan Tera'),
('Ek Ishare Pe Tere'),
('Jhalliye Tu Rona Chad De'),
('Ek Ladki Bheegi Bhaagi Si'),
('Ek Rishta Se'),
('Ek Tarfa'),
('Ek Teri Khatir'),
('Marjaavaan'),
('Angrezi Medium'),
('Elaan'),
('Ellam Unnale'),
('El Chapo'),
('El Jatt'),
('Embassy'),
('Kasada Tabara'),
('Enakku Mattum'),
('Ena Na Staya Kar (Dunia)'),
('End Game'),
('Enemy'),
('Engagement'),
('Engine Blow'),
('Enjoy Enjaami'),
('Oh My Kadavule'),
('Ennam Pol Vazhkai'),
('Thalli Pogathey'),
('Enna Vazhka Da'),
('Teddy'),
('Yaaro'),
('Katteri'),
('Eppadi Iruntha Naanga (From &quot;Sulthan&quot;)'),
('Eppa Paarthaalum (From &quot;Aalambana&quot;)'),
('ERA'),
('Estupido'),
('Evidence'),
('Excuses'),
('Excuse'),
('Exotic'),
('Expensive Cars'),
('Expensive'),
('Ex Calling'),
('Ex Girlfriend'),
('Eyes on You'),
('Eye Shot'),
('Pushpa - The Rise'),
('Faaslo Pe'),
('Faisla'),
('Fakeism'),
('Fake A Smile'),
('Fake Brother'),
('Fake Love'),
('Fake Promises'),
('Fakira'),
('Fakira Da'),
('Student of the Year 2'),
('Falanwa Ke Beta Sapanwa Me Aata Hai 2'),
('Fallin for You'),
('Family'),
('Famous'),
('Fanaa'),
('Faniyar'),
('Fantasy'),
('Fan Fakkad Ka (feat. Subhash Fozi)'),
('Fan Look Ka'),
('Faraar'),
('Lazy POP'),
('Farak'),
('Farak Pe Geya'),
('Fariyad'),
('Farmer'),
('Farq Nahi Padta'),
('Fashion Di Definition'),
('Fashion Wala Suit'),
('Fate (The Real Story)'),
('Father Saab'),
('Fatteh Chak'),
('Fault'),
('Favourite'),
('Feelings'),
('Feeling Great'),
('Feeling Seeling'),
('Feeling You'),
('Feel Hai'),
('Vaazhl (Original Motion Picture Soundtrack)'),
('Feem Aali Dabbi'),
('King Pin'),
('Feem Afghani'),
('Feem'),
('Feem Jatti'),
('FEEM WARGI'),
('Few Days'),
('Fikar Hai'),
('Fikar Kardi'),
('Fikar'),
('Fikkar Koi Na'),
('Friends Matter'),
('Filhaal2 Mohabbat'),
('Filhall'),
('Filmaa'),
('Finally'),
('Fiqar Faridan'),
('Fiqar'),
('Fire'),
('Fire Chalde'),
('Fire Honge'),
('Fire Jatt De'),
('Fire Maare'),
('Firse Machayenge'),
('First Class'),
('First Haryanvi Drill'),
('First Kiss'),
('Fitrat'),
('Fix This (feat. Raashi Sood)'),
('Flame'),
('Flavour Hukka'),
('Floating Through Space'),
('Flood Back'),
('Flop'),
('Flying Kiss'),
('Fly'),
('Focus'),
('Fokke Laarey'),
('Follow Karda'),
('Fond'),
('Foolad'),
('Forget About It'),
('For U Jannat Skoon'),
('Freakin Love'),
('Freestyle 21'),
('Freestyle'),
('Litti Chokha'),
('Free Style'),
('Frod Balma'),
('Fulla Aali Jutti'),
('Fully Loaded'),
('Fursat Hai Aaj Bhi'),
('Future Plan'),
('Gaali Si Lagti Hai'),
('Gaal Bhulke Aagi'),
('Gaana Tere Yaar Da'),
('Gaandu Kannamma'),
('Gaani'),
('Gaani Yaar Di'),
('Gaat Me Kat - Single'),
('Gabhru'),
('Gabru Chan Warga'),
('Gabru Da Naam'),
('Gabru De Naa Karke'),
('Gabru'),
('Gabru - Kamaal Khan'),
('Ghagra'),
('Gutt'),
('G Loss'),
('G-Wag'),
('Hasdi Reya Kar'),
('Holi Mein De De Chumma'),
('Holi Mein Sadhu Aya Hai'),
('Hollari'),
('How Many'),
('Hoyi Bhatijwa Holi Mein'),
('Ishq'),
('Jack n Jill'),
('Jee Ni Karda'),
('Juda Kar Diya'),
('Kadar'),
('Karnan'),
('Kangana'),
('Kara Tani Tuhu Control'),
('Kde Kde'),
('Lahe Lahe Rangab Salwarwa'),
('Lawangiya Mirchaiya Rangihe Hamar Saiyan'),
('Lilo Chaman 3'),
('Lost Love'),
('Main Nahi Jaunga'),
('Majhe Wale'),
('Meherbaniyan'),
('Mere Angne Mein'),
('Mustang'),
('Nayan'),
('Neat'),
('Raakh Lagake Remix'),
('Ring Ring'),
('Mumbai Saga'),
('Sin'),
('Surma Bole'),
('Tenu Meri Umar Lag Jaave'),
('Tenu Ni Pta'),
('Tohar Marda Hamar Saar Lagela'),
('Tu Aa Jaana'),
('Tu Lagdi Ferrari'),
('Zara Thehro'),
('Gaddar Banda'),
('Gaddian Te Karre (feat. Jot Sekhon)'),
('Gaddiyan Black'),
('Gaddi Boldi'),
('Gaddi da Number'),
('Gaddi Neevi'),
('Gadi Kali'),
('Gairan De Suit'),
('Gajanan'),
('Gajban 2'),
('Gajban Ki Taur'),
('Gajban'),
('Galat'),
('Galat Baat'),
('Galbat'),
('Gale Lagana Hai'),
('Gallaan Teriyaan'),
('Gallan Ch Romance'),
('Gallan'),
('Gallan Dogaliyan'),
('Gallan Goriyan'),
('Gallan Hun De Waqt Diyan'),
('Gallan Ne Do '),
('Gall'),
('Gall Sun Jatta'),
('Galte Chalte Ba'),
('Galti'),
('Galti Ta Das'),
('Gal Baap Di'),
('Gal Dil Di'),
('Gal Gabru Di'),
('Gal Karke'),
('Gal Karle'),
('Gal ki aeee'),
('Gal Mardan Wali'),
('Gal Sun'),
('Gal Sun Makhna'),
('Game'),
('Game Over'),
('Gandasa'),
('Gangajal'),
('Gangmates'),
('Gangsta Blood'),
('Gangster'),
('Gangster Yaar'),
('Gangwar'),
('Garbe Ki Raat'),
('Garmi Mein Chill'),
('Garmi Non Stop Dance Mix'),
('Garmi Remix'),
('Garnetar'),
('Gayatri Mantra'),
('Gaye Jo Tum'),
('Geda Geda'),
('Gede'),
('Gediyan'),
('Gedi'),
('Gedi On Ford'),
('Gedi Route'),
('Geet'),
('Gehne Naal Taur'),
('Genda Phool (Junkilla Remix)'),
('Genda Phool'),
('Gentlemen'),
('Gerhe Te Gerha'),
('Ghaghro'),
('Ghagra 52 Gaj Ka'),
('Ghaint Ghaint Suit'),
('Ghalat'),
('Tanhaji - The Unsung Warrior'),
('Ghana Kasoota'),
('Rashmi Rocket'),
('Ghani Marod'),
('Ghar Aaja'),
('Ghar Aao Na'),
('Ghar Aaya Mera Pardesi - Ft. Ayesha Mulla'),
('Ghar Tum Hi Ho'),
('Ghatak Munde'),
('Ghat Jayi Ka'),
('Ghesla'),
('Ghoomar - Single'),
('Ghoom Ghagra - Single'),
('Ghum Ghaghra'),
('Ghunghata Uthai La'),
('Ghunghat 3'),
('Ghunghat Gori Ka'),
('Ghunghat Ka Tala - Single'),
('Ghungroo Toot Gaye'),
('Ghungroo'),
('War'),
('Ghungru'),
('Ghut Sapni'),
('Giftaan'),
('Girkana Tera Re'),
('Girkani'),
('Girlfriend'),
('Glock 32'),
('Glock'),
('Goat Dekho'),
('Goat'),
('Goa Beach'),
('Godfather'),
('God&#039;s Plan'),
('God Will Judge'),
('Takkar'),
('Golden Jatti'),
('Gold Kangan'),
('Goli'),
('Goli Wargi'),
('Gol Mol'),
('Goodfella'),
('Goodwill'),
('Good Luck'),
('Good Naai Bad Aadu'),
('Good Night'),
('Gora Gora Rang'),
('Gora Rang'),
('Goriyaan Goriyaan'),
('Goriye'),
('Gotta Go'),
('Gott'),
('Govind Bolo'),
('Go Down Deh (feat. Shaggy and Sean Paul)'),
('Go Find Out'),
('Go to Hell'),
('Graffiti'),
('Grandfather'),
('Great Gang'),
('Grind'),
('Grip'),
('Grow'),
('Gudde Guddian Da Khel'),
('Guess'),
('Guitar Vajda'),
('Gujjar Boy'),
('Gulaam'),
('Gulabi Lehenga'),
('Gulgule'),
('Gally Ki Party Latest Hindi Rap'),
('Gulu Gulu Rap Song'),
('Gumsum'),
('Gunaah'),
('Gunday Yaar'),
('Gundazone'),
('Gundeyan Di Gaddi'),
('Gunde Te Pyaar'),
('Gundumalli'),
('Gunehgar'),
('Gunghroo'),
('Guns Out'),
('Gun De Gunn'),
('Gun Matters Jigar'),
('Gun Smoke'),
('Gun'),
('Gun Warga'),
('Gurshal'),
('Guru Gobind'),
('Gussa Jatt Da'),
('Gusse Hoya Na Kar'),
('Gusse Vich'),
('Gustakhi'),
('Gutt Ch Paranda'),
('Gutt Te Naa'),
('Gut Feel'),
('Guzarishan'),
('Gym De Shokeen'),
('Marjaney'),
('Haal'),
('Haal E Dil'),
('Haami'),
('Haan Bhaldi'),
('Haan'),
('Haan Mazak Aa'),
('Haarda Ni'),
('Haare Hum Haare'),
('Haari'),
('HAAR GAYI'),
('Haasyan Ch Jaan'),
('Haaye Oye (Acoustic)'),
('Haaye Oye'),
('Haaye Rabba'),
('Habbit (feat. Simar Kaur)'),
('Habibi'),
('Habit'),
('Hadd Tod Da'),
('Hadtaal'),
('Hai Pyaar Kya'),
('Hai Tera Saath'),
('Hai Tu Kaun'),
('Haji Peer Bhoomi 2020'),
('Halo Re Halo'),
('Hamare Darmiyan'),
('Hamari Kahani'),
('Hamke Dulhin Banala'),
('Handcuffs'),
('Hanji Hanji'),
('Hanjugam (From &quot;Bhuj The Pride Of India&quot;)'),
('Hanju'),
('Happy Birthday Jatta Ve'),
('Happy Birthday My Life - Single'),
('Happy Birthday To You Ji'),
('Happy Birthday Yaara'),
('Happy New Year 2021 Dj Song'),
('Haqdaar'),
('Haqq'),
('Haq Ali'),
('Haq'),
('Hard Beat'),
('Hard'),
('Hard To Get'),
('Hare Krishna Hare'),
('Hare Krishna Hare Rama'),
('Hari Singh Nalwa'),
('Harkheya Jatt'),
('Haryana Aale'),
('Haryana Roadways'),
('Haryanvi Beat'),
('Haryanvi Chora'),
('Har Ek Pal'),
('Har Funn Maula (From &quot;Koi Jaane Na&quot;)'),
('Har Saah'),
('Hasda Reha Kar'),
('Hassna Bhuljengi'),
('Hass Ke'),
('Memax'),
('Haters'),
('Hathkadiyan'),
('Hathyar'),
('Hath Jorhe'),
('Hath Kadi'),
('Hatt Jatta Hatt (feat. Gurlez Akhtar)'),
('Hatt Ja Passe'),
('The Big Bull'),
('Hawa Aun De'),
('Hawa Banke'),
('Hawa Warga'),
('Haye Tatta'),
('Hay Gopal Krishna'),
('Hazaron Ka Kya Hoga'),
('Headline'),
('Heal'),
('Heartbeat'),
('Heartfail'),
('Heart Beat'),
('Heavy Ghaghra'),
('Heavy Gotta'),
('Heavy Hai Bhai'),
('Heeran Ke Chakkar'),
('Heera Jatt'),
('Heera'),
('Heer'),
('Heer Ranjha'),
('Kade Haan Kade Naa'),
('Helli Me Chor'),
('Hello Koun'),
('Hello'),
('Hello Priya'),
('Herogiri'),
('Hey Baby Girl'),
('Vannakkamda Mappilei'),
('Hey Singari'),
('He Loves Me'),
('Hichki'),
('Hide Karke'),
('Higher (feat. iann dior)'),
('High Range'),
('Hijab'),
('Hindustani Way'),
('Hivada Mein Rajasthan Hain'),
('Hi Jack'),
('Hobby'),
('Hokka'),
('Hold My Kamariya'),
('Holiday'),
('Holiya Me Hili'),
('Holi Mein Kunwar Ke Duwar Jhakela'),
('Holi Mein Rangeele'),
('Holi Me Bhouji Ke Rahan Bigdal'),
('Holi Me Kajal Badal Gaili'),
('Holi Patidar Ke'),
('Hollywood'),
('Hometown'),
('Homicide'),
('Hona Chaida'),
('Hone Laga Tumse Pyaar'),
('Honsle Buland'),
('Honthon Pe Bas by Mika Singh'),
('Honth Chocolate'),
('Hood (feat. Inderpal Moga)'),
('Hook N Crook'),
('Hoor Pari'),
('Hooter'),
('Hope'),
('Hora'),
('Hor Dus'),
('Hor Koi Na'),
('Hosh'),
('Hosh Mai Aa (Tadipaar)'),
('Hostel'),
('Hot Ba Tohar Figure'),
('Houdini'),
('Houli Bol'),
('Ho Balma'),
('Malang - Unleash The Madness'),
('Hug Life (Jaffiyan)'),
('Hukka'),
('Thana Sadar'),
('Hula La La'),
('Humdard Hai'),
('Humko Toh Pyaar Hogaya'),
('Humko Tum Mil Gaye'),
('Hummer'),
('Humnavva Humsafar'),
('Humsafar'),
('Hum Hindustani'),
('Hum Kalam'),
('Hum Mar Jayenge'),
('Hum Padhte Bani Ho'),
('Before You Die'),
('Hum To Tere Aashiq Hain'),
('Hum Tum'),
('Hungama 2'),
('Hunter'),
('Hun Vailpunna Chalu'),
('Husband Bawla'),
('Husna Diye Pariye'),
('Hutt Hutt'),
('Hype'),
('Ibaadat Ban Gaye Ho'),
('Ibadatan'),
('Idhuvum Kadandhu Pogum (The Healing Song) (From &quot;Netrikann&quot;)'),
('Its My Life'),
('Idli Chutney'),
('ID Password'),
('Ielts'),
('Ignore'),
('Ijazataan'),
('Ikk Kudi'),
('Ik Bol'),
('Ik Dafa'),
('Ik Din'),
('Ik Dooje Lai'),
('Ik Kudi'),
('Ik Mauka'),
('Ik Naya Khuwab'),
('Ik Tera'),
('Ik Vaari Maan Ja'),
('Ik Waari'),
('Illegal'),
('Illegal Hood'),
('Iltija'),
('Ilzaam'),
('Imma Boss'),
('Incomplete'),
('Incomplete Love'),
('Indian Army'),
('India Gate'),
('India Together'),
('Indra VS 5911'),
('INDUSTRY BABY'),
('Infamous Boy'),
('Innocent Face'),
('Inteha'),
('Interstellar'),
('Intezaar'),
('Intezar'),
('Into You'),
('Introducing Her'),
('INTRO IKIGAI'),
('Intzaar'),
('In It To Win It'),
('Azadi Ke Bad'),
('Ishaara'),
('Ishqam'),
('Ishqe Di Galliyan'),
('Ishqe Vich Aukha'),
('Ishqiya'),
('Ishqzada'),
('Ishq Bheegaye Naina'),
('Ishq Da Rog'),
('Ishq Fakeeri'),
('Ishq Farzi'),
('Ishq Gehra'),
('Ishq Hai'),
('Ishq Hai (Original Score)'),
('Ishq Hogaya'),
('Ishq Kahani'),
('Ishq Karo Dil Se (From &quot;Koi Jaane Na&quot;)'),
('Ishq Ka Mausam'),
('Ishq Ka Raja'),
('Ishq Khuda Hai'),
('Ishq Ki Barsaatein'),
('Ishq Lagan'),
('Bypass Road'),
('Ishq Mein'),
('Ishq Nachaya'),
('Ishq Nu Chhedi Na'),
('Ishq Parasti'),
('Ishq Saaf'),
('Ishq Samundar'),
('Ishq Tera Mera'),
('Ishq Te Ashiqi'),
('Ishq Tumhara'),
('Iss Pyar Ko'),
('Is Qadar Dil Mera'),
('Is Qadar'),
('Is Tarah Aashiqui Ka'),
('Itihaas'),
('Itna Bata De'),
('The Body'),
('Itraan Diya Mehkaan'),
('its All Done'),
('It&#039;s Bad Time'),
('It&#039;s My Time'),
('It&#039;s Okay'),
('It&#039;s Over'),
('Izhaar'),
('Andhaghaaram'),
('I Don&#039;t Know'),
('I Feel'),
('I Love You Kinna Sara'),
('I Told You'),
('Jaada'),
('Jaagde Raho'),
('200 Halla Ho'),
('Jaanein Bachayenge'),
('Jaaneja Dilruba'),
('Koi Jaane Na'),
('Jaane De Mujhe'),
('Jaane Meriye'),
('Jaane Meri'),
('Bob Biswas'),
('Jaanu Ji'),
('Jaan'),
('Khuda Haafiz'),
('Jaan Bula Ke'),
('Jaan Dardi'),
('Jaan (From&quot;Yes I Am Student&quot;)'),
('Jaan Jaan'),
('Jaan Jatti Di'),
('Jaan Kad Lai'),
('Jaan Ke Duaar Pa'),
('Jaan Lay Ja'),
('Jaan Leva Nakhre'),
('Jaan Panjabi 2.0'),
('Jaan Vaarda'),
('Jaan Wardi'),
('Jaate Jaate'),
('Jabardast Dost'),
('Jabb Se Tumko Dekhaa'),
('Jab Dil Mile'),
('Jab Jab Kajrawa Karelu'),
('Jab Jab Piyawa Rowayi Ho'),
('Jab Jab'),
('Jab Se Mile Ho Tum'),
('Jab Se Tu Mili Hai'),
('Jab Teri Yaad'),
('Jadon Nachdi Tu'),
('Jado Ji Ke Holi'),
('Jaguar - Single'),
('Shershaah'),
('Jail'),
('Jaimaal Mein Dhamaal'),
('Jai Baba Ki'),
('Jai Bhole Baba (Hindi)'),
('Jai Jaikaar'),
('Jai Jai Shiv Shankar'),
('Jai Kara Kedara'),
('Jai Veeru'),
('Jajbaat'),
('Batla House'),
('Jalebi Baby'),
('Jalebi'),
('Jallad'),
('Jallianwala'),
('Jamaica to India'),
('Jameson'),
('Jameson Wargi'),
('Jamme Naal De'),
('Janam'),
('Qismat 2'),
('Jandi Jandi 2'),
('Adhikar'),
('Jannat'),
('Jannat Ka Tukda'),
('Jannat Ve'),
('Satyameva Jayate'),
('Jap Naam Bhole Ka'),
('Jaqeen'),
('Jarde Jahi Naar'),
('Jashan'),
('Jattan De Jawaak'),
('Jattan Di Pachaan'),
('Jatta'),
('Jatta Ve'),
('Jatta Ve Jatta'),
('Jattiyan'),
('Jattiye'),
('Jatti Di Yaari'),
('Jatti Jeone Morh Wargi'),
('Jinne Jamme Saare Nikamme'),
('Jatti Kohenoor Wargi'),
('Jatti Lit'),
('Jatti'),
('Jatti Teri Fan'),
('Jatti Ton Pyaar Le'),
('Jatt Brand'),
('Jatt Da Swaad (feat. G.noor)'),
('Jatt De Brober'),
('Jatt De Khilaaf'),
('Jatt Di Guddi'),
('Jatt Di Pasand'),
('Jatt Di Zuban'),
('Jatt Fire'),
('Jatt Jatt'),
('Jatt Mannya'),
('Jatt Mashoor Ne'),
('Jatt Moon'),
('Jatt Naal Yaari'),
('Jatt Nikle'),
('Jatt Scene'),
('Jatt Vs Jail'),
('Jatt Yamla'),
('Jaungi Pani Len'),
('Jawab De'),
('Jawani 1984 To 2021'),
('Jawani Ke Josh Kam Karas'),
('Jawani'),
('Jazaak Allah'),
('Jazbaati Bande'),
('Jazbaat'),
('Jazzy B'),
('Ja Ab Palat Ke Dekhab Na'),
('Ja Bewafa Hamse Hoke Juda'),
('Ja Ja Ja'),
('Ja Ja Re'),
('Ja Jee Lay'),
('Ja Tiya Padhe Itwaro Ke'),
('Ja Ve Ja'),
('Jeena Bhool Jaunga'),
('Jugni (My First Album)'),
('Kutte Fail'),
('Jeep'),
('Jeep Md Desi Rockstar'),
('Yennanga Sir Unga Sattam'),
('Jeetega Mera India'),
('Jeetenge Hum'),
('Tips Rewind: A Tribute to Jagjit Singh'),
('Jee Jee Kahenga (feat. Gurlez Akhtar)'),
('Jee Karr Daa'),
('Jee Le Zindagi'),
('Jee Nai Sakdi'),
('Jeona Mour 2'),
('Jerhe Shadd Gye'),
('Je Yeshu Naal Tere'),
('Jhaaj Jeya Jatt'),
('Jhake (feat. Gurlez Akhtar)'),
('Jhakhi Daar Chubara'),
('Jhalle Kalle'),
('Jhanjar'),
('Tera Naam'),
('Jhanjhar'),
('Jhanjhar Waliye'),
('RANG'),
('Jhanjran'),
('Jhanjra'),
('Jheeni Jheeni Bhoomi 2020'),
('Jhidkaan'),
('Shakuntala Devi'),
('Jhoome'),
('Jhoomka Gira Re - Mukul And Ruchika Jangid'),
('Jhoom Baraabar Jhoomm'),
('Jhoota Lagda'),
('Jhoota Pyar'),
('Jhootha Hai'),
('Jhoothe Hain'),
('Jhooth Bolda'),
('Jhooth Bolna Paap Hai'),
('Jhooth'),
('Jhooth Vikda'),
('Jhotte Jatt'),
('Jhumka Giral Ba Chhathi Ghat Pe'),
('Jhumka Giri Bareilly Ke Bazaar Mein'),
('Jhumka'),
('Jhutha Jma Tu'),
('Jhuthi Soh'),
('Jigre'),
('Jija Saali'),
('Jija Tu Kala'),
('MGR Magan (Original Motion Picture Soundtrack)'),
('Jimmy Choo'),
('Jind Jaan'),
('Jind'),
('Jind Meriye'),
('Jind Nimani'),
('Jine De'),
('Jaani Ve'),
('Jinna Pyaar'),
('Jinna Tera Kareya'),
('Jiske Liye'),
('Jism'),
('Jiss Waqt Tera Chehra'),
('Jis Din Tum'),
('Jitt da Ailaan'),
('Jiya Kaanch Ka'),
('Jiye Na Debu Ka Ae Patarko 2.0'),
('Jodaa'),
('JODI'),
('Joganiya'),
('Joon Fakran Di'),
('Jo Chumma Degi Jitegi'),
('Jo Tera Vo Mera'),
('Jo Tumko Jhoot Lage'),
('Jo Tu Na Mila'),
('Judge Me Later'),
('Jugni Ji'),
('Jugnu'),
('Jug Jug Jeeve'),
('Juice Da Glass'),
('Julami Chundad - Single'),
('Julfan De Jaal'),
('JULLI BISTRE'),
('Julli Margi Jille Pe'),
('Junoon'),
('Juraban'),
('Jurat'),
('Justified'),
('Just A Dream'),
('Jutti'),
('Jutti Tilledar'),
('Jyada Jachdi'),
('K.V Wala Launda'),
('Kaabil E Tareef'),
('Shiva Shivaa'),
('Ganesapuram'),
('Kaadu'),
('Kaahe Ko Sataaye'),
('Ward-126'),
('Vendhu Thanindhathu Kaadu'),
('Kaala Chela'),
('Kaala Jadu'),
('Kaala Maal'),
('Kaale Kaarname'),
('Kaale Sheeshe'),
('Kaali Audi'),
('Kaali Bentley'),
('Kaali Car'),
('Kaali Gaddi'),
('Kaali Range'),
('Kaand'),
('Kaante'),
('Kaare'),
('Kaari Kaari'),
('Kaash Aisa Hota - Single'),
('Kaash'),
('Kaasu (From &quot;Raame Aandalum Raavane Aandalum&quot;)'),
('Kaathadi'),
('Maara'),
('Vanam'),
('Soorarai Pottru'),
('Kabaddi Anthem'),
('Kabala Kai Dehab'),
('Kabira'),
('Kabootar'),
('Kabza'),
('Kadar Kyo Ni Krda'),
('Kade Kade'),
('Ranga'),
('Kadi Te Has Bol Ve'),
('Kahani'),
('Kahe Tor Kareja Phatata'),
('Kahin Door Jab Din Dhal Jaye'),
('Kaise Hum Bataye'),
('Kaise Juda Rahein'),
('Kaise Kahoon'),
('Kaise Kahu'),
('Noka Noka'),
('Kajal Kala - Single'),
('Kajla'),
('Kaju'),
('Kakh'),
('Kala Chashma 2'),
('Kala Daman'),
('Kala Jodda'),
('Kala Kurta Chadra'),
('Kala Maal'),
('Kala Suit Pe Kala Chashma'),
('Kala Suit'),
('Kala Tikka'),
('Kale Ho'),
('Kale Ke Papa'),
('Kali Maserati'),
('Kalla Reh Jayenga'),
('Kalla Sohna Nai'),
('Kalle Kalle'),
('Kalle Kalle - Single'),
('Kalli BehKe'),
('Kalli Kalli Gal'),
('Kalli Kalli Raat'),
('Kalli Kalli Wish'),
('Kalyug'),
('Kal De Jawaak'),
('Kal De Jawak'),
('Kal Di Gal'),
('Kamaal'),
('Kamaal Kardi'),
('Kamaal Kare Tu'),
('Kamaal Kari Jaane O'),
('Kamariya Kaam Na Kare - Single'),
('Kamariya Turele Raja Ji'),
('Kamar Kamjor'),
('Kamar Ke Dard'),
('Kamar Ke Number Badhal Ba'),
('Kamar Lapkauaa'),
('Kamar Mein Gudgudi Barela'),
('Kamar Nahi Kaam Karata'),
('Kamar Teri Left Right Hale'),
('Kami Kithe Reh Gayi'),
('Kamla Shayar'),
('Hum Do Hamare Do'),
('KAMLI'),
('Kandha Boldiyan'),
('Kandhe Ka Woh Til'),
('Kangnaa'),
('Kangna 2'),
('Kangna'),
('Kanjoos Maahi'),
('Maraikkayar - Arabikadalin Singam'),
('Kannamma Eannamma'),
('Putham Pudhu Kaalai'),
('Naan Kadavul Illai'),
('Kanpur Wale'),
('Kanta Bai (From &quot;Sangeetkaar&quot;)'),
('Kanta Laga'),
('Karam Karde'),
('Karam'),
('Karda Mai Yaad'),
('Karde Karam'),
('Kareeb'),
('Kare Se Tang Manne Chhore'),
('Kargi Ghayal'),
('Karle Pyar'),
('Karona'),
('Kartoos'),
('Karwa Chauth'),
('Kar Gal'),
('Kar Promise'),
('Kasam'),
('Kashmiri Loyi'),
('Kashmir'),
('Kashtiya'),
('Kasiyoli'),
('Kasoor'),
('Kasuta Look'),
('Katal Mubarak'),
('Katheya Ne Rehna'),
('Katta Car Me'),
('Anandham Vilayadum Veedu'),
('Kauli Khand Di'),
('Kaun Disha Mein Leke Chala - Upbeat'),
('Kaun Hai Ye'),
('Kaur Sardarni 2'),
('Kehar Jatt Da'),
('Keh Du'),
('Keh Nai Hoya'),
('Khabar Meri Maut Ki'),
('Khabar Nahi'),
('Khabbi Seat'),
('Khadkaye Hoye Aa'),
('Khad Tainu Main Dassa'),
('Khaike Paan Banaras Wala - Ritesh Pandey'),
('Khair Ki Jholi'),
('Khandaani'),
('Khandani Bande'),
('Khandani'),
('Khandani Vair'),
('khanne Wala Gandhi'),
('Khant vs. Moosa'),
('Khatam Hue Waande'),
('Khatam Karona'),
('Khatra'),
('Khat'),
('Khayaal'),
('Velle'),
('Khelab Aaj Holi Kehu Naahi Boli'),
('Khelegi Kya?'),
('Khelta Ja'),
('Khel'),
('Khesariya Awara Nahi Hai'),
('Khetibadi (feat. Gurlez Akhter)'),
('Khichi Rakh'),
('Khideya Punjab'),
('Khona Hai'),
('Khono Dardi'),
('Khoobian'),
('Dhamaka'),
('Khoya Raha'),
('Khudara Aakar'),
('Khuda kI Inayat'),
('Khudka'),
('Khudkhushi'),
('Khud Ka Pata'),
('Khuja Mat'),
('Khumariyaan'),
('Khushiyan'),
('Khushi Jab Bhi Teri (Feat.Khushalii Kumar)'),
('Khushi Viaah Di'),
('Khutti'),
('Khwahish (Dastaan)'),
('Khwahish'),
('Khwaish'),
('Khyaal'),
('Khyaal Karlo'),
('Khyaal Karlo (Cover)'),
('Kidda Fer Hatero'),
('Kids Rap Tat Tara Ra'),
('Kikli'),
('KILLA'),
('Killer Queen'),
('Killeyan Da Villa'),
('Kill Chori'),
('Kinaare'),
('Kingdom'),
('KING KONG'),
('King Life'),
('King of Majha'),
('King Queen'),
('Kinna Chauna'),
('Kinna Chir'),
('Kinna Mardi'),
('Kinne Aye Kinne Gye 2'),
('Kinne Aye Kinne Gye'),
('Kinne Saalan Baad'),
('Kinnia Choriyan'),
('Kinni Kinni Vaari'),
('Kirpana'),
('Kisaani Lipi'),
('Kisaan'),
('Kise De Kol Gal Na Kari'),
('Kismat Teri'),
('Kiss Me Like You Miss Me'),
('Roohi'),
('Kitaab'),
('Kitabaan Vich'),
('Kithe Dil La Leya'),
('Kitkat Jawani'),
('Kitna hai pyaar'),
('Kitthe Chali'),
('Ki Bann Da'),
('Star-crossed'),
('Ki Kariye'),
('Ki Lagdi Teri'),
('Ki Tusi Jande O (feat. Singga)'),
('Arasiyalla Idhellam Saadharnamappa'),
('Kohinoor'),
('Koi Aur Hai'),
('Samarjeet Randhava&#039;s Sufi Rockland'),
('Sonu Tey Papa Di Gaddi'),
('Koi Fariyaad Unplugged'),
('Koi Gham Nahi'),
('Maidan-E-Jung'),
('Koi Hor'),
('Koi Mull Nahi'),
('Koi Nahin'),
('Koi Na'),
('Koi Sehri Babu'),
('Koka'),
('Koke'),
('Kol Hove'),
('Konjam Pesu'),
('Koshish Karne Walon Ki Haar Nahin Hoti'),
('Kothe Chad Lalkaru'),
('Kothi'),
('Krk Kutta'),
('Kuch Aisa'),
('Kuch Bhi Ho Jaye'),
('Kuch Kuch'),
('Kuch nhi kehndi'),
('Kudiya De Layi'),
('Kudi Chandigarh Di'),
('Kudi Himachal Di'),
('Minnal Murali'),
('Kunba'),
('Kunde Taale'),
('Kunware Mein Rang Lagwaile Bani'),
('Kurbaan'),
('Kuri Tu Mean Hai'),
('Kursi bin Table'),
('Kurta Daman'),
('Kurta Pajama (From &quot;Sangeetkaar&quot;)'),
('Kurti'),
('Kuruthi Aattam'),
('Satyameva Jayate 2'),
('Lut Gaye - Jubin Nautiyal'),
('Kutty Pattas'),
('Kya Baat'),
('Kya Hua Tera Vada'),
('Kya Karu'),
('Broken but Beautiful Season 3'),
('Kya Mujhse Pyar Karte Ho'),
('Kya Rakha Hai'),
('Kyon 2020'),
('Kyon Dardi'),
('Kyun Bewajah'),
('Kyun Ki Tu'),
('Kyu Ruwauna Ae'),
('Kyu Soniya'),
('K Haal Hai'),
('Laada ka Lada'),
('Laadle 3 - Single'),
('Laadu'),
('Laagi Lagan Shankara'),
('Laalaan Dian Shahaadtan'),
('Laala Laala'),
('Laali'),
('Laali Thamja'),
('Laal Dupatta'),
('Laal Gulabi'),
('Laal Hari Peeli Choodiyan'),
('Laambo Ghunghat'),
('Laapata'),
('Laarey'),
('Laare And Prada'),
('Laare Da Ki Kariye'),
('Laare'),
('Laddo Hogi Syani'),
('Laddu Laddu Kehke'),
('Ladka Alag Sa'),
('Ladki Bigad Gayi'),
('Ladoo Return'),
('Lafanga'),
('Lagann Laagii'),
('Krishna Bhajan - Lagan Tumse Laga Baithe'),
('Lagdi Thaa'),
('Laggi Payi Aa 26'),
('Lag Ja Gale - Siddharth Slathia'),
('Lag Raha Hai Dil Deewana'),
('Lahangwa Las Las Karta'),
('Lahore'),
('Lahori Jatti'),
('Lahu Di Awaaz 2'),
('Lahu Di Awaaz'),
('Laija Laija'),
('Laiki Ke Line Laag Jaai'),
('Laila'),
('Laiyan Laiyan'),
('Lakeerain'),
('Lakeeran (From &quot;Haseen Dillruba&quot;)'),
('Lakhmichand Ki Tek'),
('Lak Patla'),
('Lala Lala Lori'),
('Lalkaare (From &quot;Honsla Rakh&quot;)'),
('Lal Lal Hothwa Se - Upbeat'),
('Lambarghinii'),
('Lamborghini'),
('Lamhe'),
('Lamhe Zaroori'),
('Lanka Lutegi'),
('Lara Sohneya'),
('Last Peg'),
('Lattu - Single'),
('Launda Sakth Hai'),
('Laungan Da Guchha'),
('Laung Digya'),
('Laung Gawaacha'),
('Lazeez'),
('Lean On'),
('Left Seat'),
('Lehanga'),
('Lehar'),
('Lehar Vibe'),
('Lehenga Lyade Mehnga'),
('Lehenge Aala Naap'),
('Lehja'),
('Leja Leja Re Mahi'),
('Len Den Ke Chakkar'),
('Let&#039;s See'),
('Letter To An Angel'),
('Let Me Know'),
('Let Them Count'),
('Le La DUI Rupaiyan'),
('Le Li Ego Chumma'),
('LG Da Round'),
('Lifeline'),
('Lifestyle (feat. Adam Levine)'),
('Lifestyle'),
('Dear DAD'),
('Liggi'),
('Detour'),
('Likhari'),
('Sanam - Likhe Jo Khat Tujhe'),
('Lilo Chaman 2 - Single'),
('Lil Bruh'),
('LimeLight'),
('Link'),
('Listen Bro'),
('Listen Me'),
('TRIPLEE SIXX PART 1'),
('Little Star'),
('Lit Guyz'),
('Living Legend'),
('Loaded Gun'),
('LOCATION'),
('Loca'),
('Lockdown Love'),
('Loco'),
('Log Kya Kahenge'),
('Aranmanai 3'),
('Ginny Weds Sunny'),
('London'),
('London Lahore'),
('Long Drive'),
('Long Nights'),
('Look Behind'),
('Look Innocent'),
('Look'),
('Lootera'),
('Looteri'),
('Loot Liya'),
('Lor'),
('Lost Home (feat. Mr Dee)'),
('Love Birds'),
('Love Forever'),
('Love Kardi'),
('Love Talks'),
('Love To You'),
('Love With You'),
('Love You'),
('LPK Love Passion Karma'),
('Luck Di Kasam'),
('Neighbours'),
('Lut Gaye'),
('Maachis'),
('Maaf Karde'),
('Maahiya'),
('Maahi Kithe'),
('Maalik'),
('Maalik Ghulam'),
('Maalik Mere'),
('Maalko'),
('Maal Maal'),
('Maangi Duaein'),
('Maan Taan Ja Kar Deo'),
('Maan Wajjda'),
('Maar hi Dalogi'),
('Maar Thumke'),
('Maatam'),
('Maavan'),
('Maa Baap'),
('Maa Boli'),
('Maa Da Dil'),
('Maa Gujri'),
('Maa Ki Laadli'),
('Machayenge 3'),
('Machayenge'),
('Machhli'),
('Machis Ke Tilli'),
('Mayan'),
('Machi Naveen'),
('Machlo'),
('Madam'),
('Made In Haryana'),
('Madhanya'),
('Madhubala'),
('Madhuban'),
('Mad For You'),
('MAFIA'),
('Mafia Style'),
('Mafia Trade'),
('Magazine'),
('Magizhini'),
('Magnum'),
('Mahadeva'),
('Mahal'),
('Mahaul Bana'),
('Mahiya'),
('Mahi Ve'),
('Mahoul'),
('Maine Royaan'),
('Mainu Dasde'),
('Main Balak Tu Mata'),
('Main Bhi Barbaad'),
('Main Dhoondta Raha'),
('Main Gate Band Baduwe'),
('Main Hoon Na Tere Saath (From &quot;Saina&quot;)'),
('Main Janu Na'),
('Main Jis Din Bhulaa Du'),
('Main Ki Kara'),
('Main Marjaunga'),
('Main Pyaar Mein Hoon'),
('Main Sharabi'),
('Main Tera Hoon'),
('Main Tera Ho Gaya'),
('Main Teri Hoon'),
('Main To Kahun'),
('Mai Ni Meriye'),
('Mai Pardesan Hona'),
('Mai Te Oh'),
('Majak Thodi Ae'),
('Majanuaa Pitata'),
('Majboori'),
('MAJHAILS'),
('Majhail Fellas'),
('Majhail vs Malvain'),
('Majha Boys'),
('Majha Doaba Wale'),
('Majha Hype'),
('Majha Malwa Doaba'),
('Majhe Aale'),
('Majhe Walde'),
('Majnu'),
('Makeup Wala Mukhda'),
('Malki Keema'),
('Malta'),
('Malum Hai Na (Intro)'),
('Malwa Belt'),
('Malwa To Miami'),
('Mama'),
('Mama Mia'),
('Mangar Ke Paricha Jayib'),
('Manike Mage Hithe'),
('Maniyar'),
('Manmaniyan'),
('Mannat'),
('Electro Folk Series with Ghibran'),
('Mannda Ee Ni (feat. Happy Raikoti)'),
('Manne Babu Bol'),
('Jai Bhim'),
('Mann Bawara Hua'),
('Panipat'),
('Mansa Zile Da Munda'),
('Manzil'),
('Man Ke Thanda Li'),
('Man Ki Baat'),
('Marab Thariya Phek Ke'),
('Marda Chhod Gaya'),
('Marjaani'),
('BellBottom'),
('Marjaneya'),
('Marjawaan'),
('Marod'),
('Marry Me'),
('Marudhaani (From &quot;Annaatthe&quot;)'),
('Maruti'),
('Masakali 2.0'),
('Mashallah'),
('Maske'),
('Masla'),
('Masle'),
('Masoom Jinda'),
('Masstaani'),
('Mastani'),
('Masterpiece'),
('Mast Malang'),
('Kabaad The Coin'),
('Mast Patola'),
('Matakni'),
('Math'),
('Matki'),
('Matlab'),
('Matthe Te Chamkan'),
('Mat Ched Balam'),
('Mat Kar Maya Ko Ahankar'),
('Mauja'),
('Maujood Hai'),
('Mauka - E Waardaat'),
('Mauka Hai'),
('Maula'),
('Mausam'),
('Mauser'),
('Maut Nachdi'),
('Sabhaapathy'),
('Maybelline'),
('Mazaa'),
('Oomai Sennaai'),
('Ma Belle'),
('Mecha'),
('Mehantan De Fal'),
('Mehbooba'),
('Mehbooba Ji'),
('Mehendi'),
('Mehendi Ka Ranngg'),
('Mehendi Lagi'),
('Meherezylaa (From &quot;Maanaadu&quot;)'),
('Meherma'),
('Mehkhana'),
('Mehmaan (Tunka Tunka)'),
('Mehndiyan'),
('Mehndi Te Vavi'),
('Mehnge Mehnge Jatt'),
('Mehnge Suit'),
('Mehnta'),
('Mehraru Humar Sunar'),
('Mehrbaniaan'),
('Mehsoos Kiya Hain'),
('Mein Tera Humsafar'),
('Melt in My Touch'),
('Memories'),
('Mental'),
('Mera Babu - Single'),
('Mera Bhai Gulzaar'),
('Mera Bhai Tu 2.0'),
('Mera Bhai Tu'),
('Mera Dil Bhi Kitna Pagal Hai'),
('Mera Dil'),
('Mera Dil Pahadon Me'),
('Mera Good Luck'),
('Mera Haal'),
('Mera Jee Karda'),
('Mera Mahi'),
('Mera Pehla Pyaar'),
('Mera Piya'),
('Mera Pyaar'),
('Mera Sardar'),
('Mera Yaar'),
('Mercy'),
('Mere Ala Ror'),
('Mere Baad'),
('Mere Baare (feat. Gurneet Dosanjh)'),
('Mere Bhai Log'),
('Mere Daman Aali Jhol'),
('Mere Dil Diyan Sunniya'),
('Mere Dil Vich'),
('Mere Geli'),
('Silence'),
('Mere Liye Anmol Tu'),
('Mere Meharbaan'),
('Mere Saaiyaan Ji'),
('Sanam - Mere Samnewali Khidki Mein'),
('Mere Sanam'),
('Mere Sohne Soniya'),
('Mere Wala Jatt'),
('Mere Wala Sardar'),
('Mere Wangu'),
('Mere Yaaraa (From &quot;Sooryavanshi&quot;)'),
('Mere Zehen Mein (From &quot;Bekhudi&quot;) - Single'),
('Meri Aashiqui'),
('Meri Baari'),
('Meri Dhadkan'),
('Meri Galti'),
('Meri Jaan'),
('Meri Ki Majaal'),
('Meri Maa Ke Barabar Koi Nahi'),
('Meri Marzi'),
('Meri Mohabbat'),
('Meri Mohobbat'),
('Meri Parchayi'),
('Meri Pukaar Suno'),
('Meri Sohniya'),
('Meri Zindagi Mein'),
('Mewati Hai Hum'),
('Mexico'),
('Mhari Tor Dekhiyo'),
('Middle Class'),
('Middle Class Munda'),
('Middle Finger'),
('Mijaj Sankawelu'),
('Milaa Yun (From &quot;Haseen Dillruba&quot;)'),
('Milky'),
('Milky White'),
('Milo Na Tum - Gajendra Verma'),
('Mil Geya Jatt'),
('Mil Ke Jaani Aan'),
('Mil Mahiya'),
('Minor'),
('Mintan'),
('Miracle'),
('Mirage'),
('Mira'),
('Mirchi'),
('Misaal'),
('Missing You'),
('Miss Ta Krengi Tuvi'),
('Miss Use'),
('Miss World'),
('Miss You'),
('Miss You Enna Sara 2'),
('Miss you enna sara'),
('Mis Reglas'),
('Mitha Bolke'),
('Mitha Mitha'),
('Mithe Bol'),
('Mithi Jahi'),
('Mithi Mithi Baarish'),
('Mithi Mithi'),
('Mitran De Charche (feat. Bakshi Billa)'),
('Mitran Kol Teri Yaad'),
('Mitti'),
('Mitti Di Khushboo'),
('Mittran Da Naa'),
('Mittra&#039;n Di Pagg Warga'),
('Miya Biwi'),
('Mi Amor'),
('Modde Te'),
('Modern Ranjha'),
('Mohabat'),
('Mohabbat Ab Bechata'),
('Sayonee'),
('Mohabbat Badnaam'),
('Mohabbat Hai'),
('Mohabbat Hai Tumse'),
('Mohabbat Phir Ho Jayegi'),
('Mohabbat'),
('Mohabbtan'),
('Mohali Waliye'),
('Mohtarma'),
('Moj Darling'),
('Monalisa'),
('Monday'),
('Mood'),
('Mood Happy'),
('Mood Pichkari Ke'),
('Moonlight'),
('More Saiya Ji Se Ke Sughar Ba'),
('Morni'),
('Mor'),
('Mota Jaib Ho'),
('Valimai 2021'),
('Mouser Wargi'),
('Move Your Body'),
('Mr. Haryana'),
('Muchha Aala Yaar'),
('Muchha Wale'),
('Muchh Diyan Fan'),
('Mudde Ute Aa'),
('Muh Mare Raja'),
('Muh Torh Dungi'),
('Mujhe Peene Do'),
('Mujhko Mana Lena'),
('Mujhse Bura Na Koi'),
('Mukammal'),
('Mukdi Gal'),
('Mukhdaa'),
('Mukhiya Ji'),
('Mukh Tera'),
('Mulajedari'),
('Mulakaat'),
('Mulakaat Jattiye'),
('Mulakat'),
('Mulakh'),
('Mulaqaat'),
('Mulaqat'),
('Mull Tardu'),
('Munda Grewala Da'),
('Munda Gucci'),
('Munda Like Karda'),
('Munda Takda'),
('Mundeer'),
('Mundeya Ve'),
('Munde Desi'),
('Munde Mere Shehar De'),
('Muraliya'),
('Murga Murgi Ki Noutanki'),
('Murphy Aala Radio - Single'),
('Yaadhum Oore Yaavarum Kelir'),
('Musafir '),
('Muscle Caran'),
('Music Mera'),
('Muskura Ke Chali Gayi'),
('Parris Jeyaraj'),
('Mutiyaar'),
('Mutiyare ni'),
('Mutiyar'),
('My Block'),
('My City'),
('My Hommies'),
('My Hood'),
('My Lady'),
('My Mum'),
('My Rulez'),
('My Talk'),
('My Time'),
('My Way'),
('M-Town'),
('Naach Meri Rani'),
('Naach Re Patarki'),
('Naad E Ali'),
('Naagin Dance'),
('Naagin Jaisi Kamar Hila (From &quot;Sangeetkaar&quot;)'),
('Naagin'),
('Naagni'),
('Bala'),
('Naal Naal'),
('Naam Ada Likhna'),
('Naam Tera'),
('Naam'),
('Naanga Vera Maari (From &quot;Valimai&quot;)'),
('Naanke'),
('Theeni'),
('Naan Thoda'),
('Naar Ni Dekhi'),
('Naa Chalda'),
('Naa Dooja Koi'),
('Nachdi'),
('NachLai Goriye'),
('Nachna Pau'),
('Nachunga Aise'),
('Nachungi Jaroor'),
('Nach Ke Malkini'),
('Nagin Dance'),
('Nagni'),
('Nahi Jaana'),
('Nahi Jandi'),
('Nahi Milni'),
('Naina Morey'),
('Naina Tu Behna Tu'),
('Nainital K Jhumke'),
('Nainowale Ne'),
('Nain Bandhe Naino Se (From &quot;Thalaivii&quot;)'),
('Nain Bengali'),
('Nain Bolde'),
('Nain Matakka'),
('Nain Nain'),
('Naiyo Lagna'),
('Naiyyo'),
('Nai Chaida'),
('Nai Chaidi'),
('Nai Jaana'),
('Nai Jeena'),
('Nakhra'),
('Nakhre Aali'),
('Nakhre'),
('Nakhre Tere'),
('Nakhro'),
('Nakkhre'),
('Nakk Te Makhi'),
('Name'),
('Nammazann'),
('Kedarnath'),
('Nanado Ke Bar Ba Nathuniya'),
('Nanad Ke Beer'),
('Nanak Naam'),
('Nanchaku'),
('Nandi Ka Bira'),
('Nandi Ke Beera'),
('Bansuri'),
('Nankana'),
('Naqaab'),
('Narak - Marichika'),
('Narrow Suit'),
('Nasha'),
('Nasha Hai'),
('Nasheeli Nasheeli'),
('Nashile Nain'),
('Nashili Lage'),
('Nasty'),
('Natpu (From &quot;RRR&quot;)'),
('Nattiya'),
('Natural Beauty'),
('Nature'),
('Naulakha - Single'),
('Nava Saal'),
('Nava Yaar'),
('Navratri Ki Aai Hai Pavan Ghadi'),
('Nazaare Luttne'),
('Nazaraa'),
('NAZAR'),
('Nazar - Single'),
('Nazraan'),
('Nazran'),
('Na Baba Na'),
('Na Cher Malangaan Nu'),
('Na Hai Meri Khata'),
('Na Hona Tumse Door'),
('Na Ja Tu'),
('Na Karde'),
('Na Maar'),
('Na Mai Hu Na Tu - Single'),
('Na Manzoori'),
('Na Nai Sunna'),
('4AM'),
('Na Na Jatta'),
('Na Na'),
('Na Na Na'),
('Na Ni Keh Sakdi'),
('Na Puch Ke'),
('Na Re Chhora'),
('Na Ye Dada Na Ho'),
('Necklace'),
('Nedey Nedey'),
('Need To Know Now'),
('Need You'),
('Neela 60'),
('Neela Ford'),
('Neeliya Akhan'),
('Neendo Se Breakup'),
('Sarpatta Parambarai'),
('Arun Vijayin Borrder'),
('New Days'),
('New Love'),
('Night Life'),
('Nikaah'),
('Nikkah'),
('Nikke Nikke Khalsey'),
('Nimbu Paani'),
('Nine1'),
('Niranabasi'),
('Nirbhau Nirvair'),
('Nishaniyan'),
('Nishani'),
('Niven Niven Suit'),
('Ni Jana'),
('No1 Yaari Ka Comeback'),
('Nobody Like You'),
('Non Stop Bollywood Dandiya-2021'),
('Nose Pin'),
('Notaan Wali Dhauns'),
('Note Gulabi'),
('Note vs Dollar'),
('Nothing Else'),
('Notorious'),
('Notorious Jatt'),
('Noxious Jatt'),
('No Chase'),
('No Doubt'),
('NO LOVE'),
('NO MORE SHADA'),
('No No No No'),
('No One'),
('Number'),
('Number Likh'),
('Oceana'),
('Made in China'),
('Official Story'),
('Off'),
('Og'),
('Ohh Maa'),
('Ohi Jatt'),
('Ohi Munda'),
('Ohi Ohi Jatt'),
('Oh Bewafa'),
('Oh Hubby Ji (feat. Mr Mrs Narula)'),
('Oh My God'),
('Oh Na Reha'),
('Oh Pind'),
('The Power'),
('Oh Sanam'),
('Ok - Single'),
('Ok Report'),
('OK Report '),
('Olympic'),
('Om Namah Shivay'),
('One Life Baby 2'),
('One Life'),
('One Sided'),
('One Wish'),
('Only Jatts'),
('On My Way'),
('Oosingo'),
('Oot Patangi'),
('Oppa Oppa'),
('Ore Piyaa Re'),
('Os Time'),
('Othlaliya Rauwa Muhe Lagal Ba'),
('Outfit'),
('Outlaw'),
('Out of Control'),
('Out Of Range'),
('Out With Doubt'),
('Ova'),
('Over You'),
('O Dilbar Yaara'),
('O Jaanwaale'),
('O Mere Channa Vey'),
('O Mere Dil Ke Chain - Shahid Mallya And Parry G'),
('O Pushpa I Hate Tears'),
('O Raahi'),
('O Saiyyonii'),
('O Sajnaa'),
('P.H.K.M'),
('Paagall'),
('Paagal'),
('Paagla'),
('Paagla (From &quot;Qismat 2&quot;)'),
('Paanch Sakhi - Single'),
('Paani Mai'),
('Paani Paani'),
('Paas Aao Na'),
('Paa Jhappiyaan'),
('Paa Peg'),
('Pabb Chak Ke'),
('Pablo'),
('Pachak Ladki'),
('Pachdi Ni'),
('Pachtaoge'),
('Pagala'),
('Pagalpan'),
('Pagal Jeha'),
('Pagal Na Hojawa'),
('Pagal Sa Rapper'),
('Paggan Tediya'),
('Pagla Pagli 3 Rap Song'),
('Pagli Paani Mein'),
('Pag Ghunghroo Baandh - Khesari Lal Yadav And Shilpi Raj'),
('Paindoo'),
('Paint'),
('Pain Killer'),
('Pajeb'),
('Pakeezgi'),
('Pakkam Neeyum Illai'),
('Palazzo 2'),
('Palazzo'),
('Pangebaaz'),
('PANGHAT'),
('Panjan Wala Note'),
('Panjeb'),
('Panj Satt Yaar'),
('Panwa Jas Badanawa'),
('Papahia'),
('Papa'),
('Dandiya Mashup'),
('Paranda'),
('Para Ceta Mol'),
('Para Rum Pa'),
('Parche'),
('Parche Return&#039;s'),
('Pardesi'),
('Pardhangi'),
('Parinda (From &quot;Saina&quot;)'),
('Pariya Diye Jaiye'),
('Parmanu Bumb'),
('Paro'),
('Parshawan'),
('Partition 1947'),
('Party Ho Rai Hai'),
('Party Mashup'),
('Pasand Aaya'),
('Pasand Bangi'),
('Pasand Bate Tore'),
('Pasand Tu Ve'),
('Patake'),
('Patakha'),
('Patari Kamariya'),
('Pata Nahio Lagda'),
('Patbijna'),
('Patiale Wala (feat. Sudesh Kumari)'),
('Patience'),
('Patla Dupatta'),
('Patli Kamariya'),
('Patli Patang'),
('Patole'),
('Patta Goli Ka'),
('Patthar Ke Sanam'),
('Patthar Wargi'),
('Patwaran'),
('Patwari'),
('Pauni Pauni'),
('Pauve Da Nasha'),
('Payala Ka Joda - Single'),
('Payal Chandi Aali 2'),
('Payal Chandi Ki 2'),
('Payal Chandi Ki'),
('Payal'),
('FIR'),
('PAYBACK'),
('PCR'),
('Peele Peele'),
('Peene Lage Ho'),
('Peg Maar Ke'),
('Peg Marungi Jaroor'),
('Pehla Nasha - Raj Barman And Rashmi Poddar'),
('Pehla Pyaar'),
('Pehla Pyar'),
('Pehla Wale 2'),
('Pehle Pyaar Ka Pehla Gham (Feat. Khushali Kumar)'),
('Pehredaariyan'),
('Pekyaan Nu'),
('Perfect'),
('Perfect Choice'),
('Per Aazhi (From &quot;Memories&quot;)'),
('Peshi (feat. Shree Brar)'),
('Petrol Pump'),
('Pe Pe Ke'),
('Phantom'),
('Phir Aaoge'),
('Phir bhi aas lagi hai 2.0'),
('Phir Mohabbat'),
('Phir Se Tu Aa'),
('Phir Tu Kyu Mainu'),
('Haseen Dillruba 2021'),
('Phone'),
('Phone Te Ishq'),
('Photoan'),
('Photo'),
('Phull'),
('Phutte Kam'),
('Piliye Me Pistol'),
('Pinch'),
('Pincode'),
('Pinda Aale'),
('Pind Baluchi by Shahid Mallya'),
('Pind Ch Charche'),
('Pind Khali Lagda'),
('Pind Mera'),
('Pind'),
('Pind To Valayat'),
('Pink Pink'),
('Pistol'),
('Pittal Da Raund'),
('Pittal'),
('Piyaji Dekho'),
('Piya Jhumke La De'),
('Piya Ji Ke Sanng'),
('Piywa Ke Mushki Pe'),
('Pi Ke Likheya Ae'),
('Playboy'),
('Play Date'),
('Plus 2 Pass'),
('Plus 6 Foot'),
('Police Mulajam'),
('Pothanur Thabal Nilayam'),
('Pounda Wale Sheikh'),
('Power (From &quot;Jai Bhim&quot;)'),
('Prada'),
('Prahune'),
('Praise'),
('Prathana Hum Na Haare Kabhi'),
('Premawa Se Bolo Happy New Year'),
('President - Warning'),
('Pressure'),
('Private Jatt'),
('Promises'),
('Promise'),
('Proof'),
('Provide'),
('Pro Jatts'),
('Psycho'),
('Puadh'),
('Public Place'),
('Puchho Na'),
('Pudina Ke Chatni'),
('Pumped Up'),
('Punjab'),
('Punjab Mere Layi'),
('Punjab to Surrey'),
('Purana Punjab Chapter 1'),
('Purbi Bayriya'),
('Purchase Pyar'),
('Putt Jattan De'),
('Puzzle Life'),
('Pyaar...Ek Tarfaa'),
('Pyaar Chahiye'),
('Pyaar (From &quot;Yes I Am Student&quot;)'),
('Pyaar Hai Mera'),
('Pyaar Ho Gya'),
('Pyaar Ho Jayega'),
('Pyaar Kari Jaane O'),
('Pyaar Karona'),
('Pyaar Karte Ho Na'),
('Pyaar Karugi'),
('Pyaar Ke Saleeqe'),
('Pyaar Non-Veg'),
('Pyaar V Karna Sikhle'),
('Pyarr Tumse'),
('Pyar Chalda'),
('Aasra'),
('Pyar Diyan Rahan'),
('Pyar Di Hawa'),
('Pyar Di Kahani'),
('Pyar Hoya Ae'),
('Pyar Hoya'),
('Sanam - Pyar Hua Chupke Se'),
('Pyar'),
('Pyar Karke'),
('Pyar Kar Di'),
('Pyar Ka Nasha'),
('Pyar Ke Saboot'),
('Pyar Mangda'),
('Pyar Mein Bapawa Diwar Bhail Ba'),
('Pyar Mera'),
('Pyar Ni Karda'),
('Pyar Tera'),
('Pyar Wali Gall'),
('Qaafira Ve'),
('Qadar Na Jaani'),
('Qatal'),
('Warning'),
('Qatra'),
('Qubool'),
('Queen'),
('Qurbaan Hua'),
('Qurbaan'),
('Raahi (Tunka Tunka)'),
('Raaji Bolja Chhod De Narajgi - Single'),
('Raakhi Karda'),
('Raamam Raaghavam (From &quot;Rrr&quot;)'),
('Raanjhana'),
('Raat Baki'),
('Raat 2021'),
('Raat Ka Kajal'),
('Raat Saari'),
('Trance'),
('Raazi'),
('Rabba Maine Chand Vekhya'),
('Rabba Ve'),
('Rabb Di Khoj'),
('Rabb Jane'),
('Rabb Manaya'),
('Rabb Wangu'),
('Rab Ne Jo Pucha'),
('Radar'),
('Radha'),
('Radha Rani'),
('Radha (Unconditional Love)'),
('Radhe Radhe'),
('Radhe Tere Charno Ki'),
('Rafal Sarane'),
('Raflan Te Botlan'),
('Rafta Rafta'),
('Rahat'),
('Rahiye Hasde'),
('Rail Ki Bhambhiri (feat. Sapna Choudhary &amp; Keshav Dev Sheru)'),
('Rail Me Dhakke Laage Se'),
('Do Vail'),
('Raja Ji Ke Jawab Naikhe'),
('Raja Ji Khoon Kaida'),
('Raja Ji'),
('Raja Rani'),
('Rajdulaari'),
('Rajinama '),
('Rajwade Jatt'),
('Rakaan'),
('Rakhdi'),
('Rakh Haunsla (Tunka Tunka)'),
('Rampyari'),
('Ram Ram'),
('Ram Tumhara Naam'),
('Rande Malang'),
('Rangava Laga Ke Jaan Bhula Gaeel'),
('Rangbaaz Loverwa'),
('Rangdar Piywa'),
('Range'),
('Rangle Dupatte'),
('Rang Barse'),
('Rang Choli Mein Lagake Devara'),
('Rang Ishq Ka'),
('Rang Ja'),
('Rang Lagaya Tune'),
('Rang Lageya'),
('Rang Roop'),
('Rang Sawla'),
('Rani Cypher'),
('Ranjhana'),
('Ranjha'),
('Ranjha (Reprise)'),
('Rapat'),
('Rapchics'),
('Rara Riri Rara Reloaded'),
('Raula (feat. Gurlez Akhtar)'),
('Raule Gaule'),
('Raule'),
('Raund 2.0 (feat. Singga)'),
('Raund'),
('Ravan Ravan Hoon Main'),
('Razzi Bolja'),
('Reality Check'),
('Reason'),
('Record Breaker'),
('Record'),
('Record Torde'),
('Red Alert'),
('Red Eyes'),
('Red Nose'),
('Red Rose'),
('Red Suit'),
('Reejh'),
('Reelan'),
('Rees Jatt de'),
('Reetan'),
('Refer to God'),
('Refugee Jatt'),
('Regret'),
('Reham Karo'),
('Rehen De Jatta'),
('Bole Chudiyan'),
('Rehne Lage Tum Dil Mein'),
('Rehnuma'),
('Relation'),
('Reliya Re'),
('Remand'),
('Reply (From &quot;Homeland&quot;)'),
('Retina'),
('Rich Kid'),
('Ride'),
('Right Place'),
('Right to Left'),
('Rihaee'),
('Rimjhim Gire Sawan - Pranav Chandran'),
('Rim Jhim'),
('Shyam Singha Roy'),
('Rise'),
('Rishta Kya'),
('Rishtey vs. Telephone'),
('Rivers'),
('Riwaz'),
('Roam Roam'),
('Roar'),
('Roar (Dahaad)'),
('Roar Of Rajput'),
('Robbery'),
('Rockstar Live'),
('Roka'),
('Roko Roko'),
('Rok De Mitarr'),
('Rok Lai'),
('Rolex'),
('Roll Up'),
('Romantic Raja'),
('Rona Likha Tha'),
('Rona Nahi'),
('Rona Paina'),
('Rondan Di Petti'),
('Rondi Car'),
('Ronna Hi Si'),
('Ron Na Deva'),
('Roohan Diyan Yaariyan'),
('Rooh'),
('Rooh Da Hani'),
('Roop Ka Palka'),
('Rotiyan'),
('Roti'),
('Rough Tone'),
('Round'),
('Rovaan Layi'),
('Rovan Tenu Yaad Karke'),
('Royal Rumble'),
('Royal Walk'),
('Roya Main'),
('Roye Na'),
('Royi Na'),
('Ro Ro Ke'),
('rubberband'),
('Rubicon'),
('Ruger'),
('Ruhama'),
('Ruk Ja Zara'),
('Rula Ke Gaya Ishq'),
('Rule Mere'),
('Rum Te Gum'),
('Runak Jhunak'),
('Rusdi Naa'),
('Russe Tu'),
('Russian Barrel'),
('Russian Weapon'),
('Russi Nu Mnaa Laina'),
('Russ Jani Aan - Single'),
('Rus Rus Ke'),
('Ruttan'),
('Rwaun De Layi'),
('Saab (From &quot;Yes I Am Student&quot;)'),
('Saada Bewafa'),
('Saade Siro'),
('Saadh Banda'),
('Saadi Marzi'),
('Saagar Paar'),
('Saah Banke'),
('Saah Chalde'),
('Saah (Tunka Tunka)'),
('Saak'),
('Saale Darde'),
('Saanwal'),
('Saara Din'),
('Saara India'),
('Saara Kaattrae (From &quot;Annaatthe&quot;)'),
('Saari Ki Saari 2.0'),
('Saari Raat'),
('Saasre Ka Rang (2021)'),
('Saas Tharo Choro'),
('Saath Kya Nibhaoge'),
('Saath'),
('Saat Samundar Paar'),
('Saawariya'),
('Saazish'),
('Sabte Unchi Haveli'),
('Saccha Wala Love'),
('Sache Wala Luv'),
('Sachiyan Yaariyan'),
('Sachi Geya Badal'),
('Sachi Suchi Raah'),
('Sach Keh Raha Hai'),
('Saddi Car Nachdi'),
('Sade Muklawe'),
('Sade Pind De'),
('Sadiya La Da Balam Kalkatiya'),
('Sadh Khushian'),
('Sad Reel'),
('Sad Song'),
('Safar Aur Baarish'),
('Safar E Shahadat'),
('Safar Ka Nasha'),
('Sagai Wala Ring Maine Tod Diya'),
('Saggi Phull'),
('Sahaare'),
('Sahi Sahi'),
('Saije Bataye Dehatu'),
('Saiyaan Bol Bhoomi 2020'),
('Saiyaan Bol'),
('Saiyaan Ji'),
('Saiyan Ke Rakhab Saari Mein Lapet Ke'),
('Saiyan Re'),
('Saiyan Satrangi'),
('Saiyyonee'),
('Sajanaa'),
('Sajda Karaan'),
('Sajda'),
('Sajjan'),
('Sajna, Say Yes To The Dress'),
('Sajna 2020'),
('Sajna Ve Sajna'),
('Sajna Ve'),
('Sajna Vi Tur Jana'),
('Sajni'),
('Sajte Ho'),
('Sakhiyaan'),
('Bell Bottom - Bollywood 2021'),
('Salaam E Ishq'),
('Salama Hundiyan'),
('Salam'),
('Saleti'),
('Salia Da Naka'),
('Salman Khan Aaya Hai'),
('Salute'),
('Samajh Na Paaogey'),
('Same as You'),
('Same Beef'),
('Samiyana Ke Saata Bhail Ba'),
('Samjho Na'),
('Samjh Ni Aundi'),
('Sample Yaara Ke'),
('Sanam Tujhko'),
('Sandhua Da Munda'),
('Sandook Tera Maye'),
('Sanjog'),
('Sanju'),
('Sanseinn'),
('Sanson Ki Mala'),
('Santa'),
('Durga Chalisa Durga Kawach'),
('Sanu Te Changa'),
('Sanwli'),
('Sapna 2'),
('Sarafa Bazar'),
('Saraswati Vandana'),
('Sardara'),
('Sardari'),
('Sardar Di Sardarni'),
('Sarkari Naukar'),
('Sarkar'),
('Saroor (From &quot;Honsla Rakh&quot;)'),
('Saroor'),
('Sasura Ji Lade Utni'),
('Sasura Mein Bhatar Dali'),
('Sasura Mein Ka Khailu Mota Gailu'),
('Sasure Se Sorry'),
('Satane Lage Ho'),
('Sathiya Tere Bina'),
('Sathi'),
('Sath Mai'),
('SATH TERE'),
('Satnam Waheguru'),
('Satrangi Piya'),
('Sau Dard'),
('Sau Putt'),
('Sau Sau Wari Khat Likhe'),
('Savage'),
('Savan'),
('Sawaal'),
('Sawaan'),
('Sawarga da Jhoota'),
('Sayonee (From &quot;Sayonee&quot;)'),
('Say Yes'),
('Sazaa'),
('Scandal'),
('Scan'),
('Scared To Love'),
('Scarface'),
('Schedule'),
('School Di Topper'),
('Scorpio'),
('Script'),
('Seat Utte Paee Tedha Tedha'),
('Secure'),
('Seedha Takeover'),
('Raame Aandalum Raavane Aandalum'),
('Sehra'),
('SEH JAAUN'),
('Sek'),
('Selfie'),
('Selfiyan'),
('Selfmade'),
('Semma Bodha'),
('Sengaatula'),
('Serious Karke'),
('Serious Matter'),
('Shaadi Hone Wali Hai'),
('Shaadi Ka Laddu - Single'),
('Shaamein'),
('Shaanti Hai Bohot'),
('Shaawa Teri Tor'),
('Shabab'),
('Shahar Aali Dhabban'),
('Shah Ji'),
('Shah Rukh Khan'),
('Shakal De Sohne'),
('Shaka Laka Boom Boom'),
('Shaman Pai Gaiyan Kesariya Balam'),
('Shambhoo Re'),
('Shankara'),
('Shanti'),
('Sharara (feat. Poonam Sood)'),
('Sharara'),
('Shardanjali'),
('Shareef Bande'),
('Shareef'),
('Shareeka'),
('Shareek'),
('Shartan'),
('Shart'),
('Shaunk'),
('Shayar'),
('Sheesha'),
('Sheesha Toot Javega - Single'),
('Sheeshe'),
('Shehar Chandigarh Chale Aa'),
('Shehar Ki Gali'),
('Shehar'),
('Sherniyan'),
('Sher Da Shikar'),
('Sher (From &quot;Honsla Rakh&quot;)'),
('Sheykhar-Rang'),
('She Bad'),
('She Don&#039;t Know (From &quot;Blessed&quot;)'),
('Shikari'),
('Shikayat'),
('Shikwa'),
('Shimla'),
('Shimmy That'),
('Shisha'),
('Shiv Chalisa'),
('Shiv Panchakshar Stotra'),
('Shiv Sama Rahe'),
('Shiv Shambho By Kailash Kher'),
('Shiv Shiv Shankara (Hindi)'),
('Shokeen'),
('Shola'),
('Shona Shona'),
('Shoot at Sight'),
('Shopping Karwade'),
('Shraab Wargi'),
('Shreaam (feat. Mr. Black)'),
('Shreaam Pagal'),
('Shri Krishna Govind Hare Murari'),
('Shukriya'),
('Shuruata'),
('Shy'),
('Side Pose'),
('Sikandar'),
('Sikha Di Kahani'),
('Sikhleya Kar'),
('Sikhya'),
('Sikka Band'),
('Silli Silli'),
('Simple Life'),
('Singh'),
('Singh Shaheed'),
('Siraa (feat. Miss Pooja)'),
('Sira Bande'),
('Sira'),
('Sira Sira'),
('Sirf Tu'),
('Sirr Fatda'),
('Sirr Polla'),
('Sitaron'),
('Sit Down'),
('Skin'),
('skip.that.party'),
('Skookum'),
('Skoon'),
('Skrrt Karenge'),
('Sky High'),
('Slay'),
('Slow Ride'),
('Slow Slow'),
('Smile Deke Dekho'),
('Snake Charmer'),
('Sniper'),
('Snitch'),
('Sochan'),
('Socha Bhi Nahi'),
('Socha Na Tha'),
('Sohna'),
('Sohna Sardar'),
('Sohnea 2'),
('Sohneya Ve'),
('Sohne Di Pasand'),
('Sohne Sohne Rang'),
('Sohni Lagdi'),
('Sohni Lagge Tu'),
('Sohn Pari'),
('Solo Laila'),
('Solva Saal'),
('Something Stupid'),
('Sonn Pann'),
('Sookha'),
('Mahaan'),
('Soorma'),
('Sorry'),
('Sorry Song'),
('Sorry Sorry'),
('Soulmate'),
('Sound De'),
('South Movie'),
('So Ja Rajkumari'),
('Speak Out'),
('Spend Life'),
('Spoiled'),
('Srinagar Waliye'),
('Stand With You'),
('Starbuck'),
('Stardom (feat. Saini Surinder)'),
('Star'),
('Star (Pradeep Pandey &#039;Chintu&#039;)'),
('Statue'),
('Stay Away'),
('Still High'),
('Still in Love'),
('Still Standing'),
('Storiyan'),
('Straight Outta Abby'),
('Straight Outta Mohali Returns'),
('Stranger'),
('Strawberry'),
('Streak'),
('Streets On Lock (feat. Gurlej Akhtar)'),
('Street King'),
('Street Talk'),
('Stronger (feat. Kesha)'),
('Struggler'),
('Student Union'),
('Success'),
('Sucha Soorma'),
('Sufi Song Qawali'),
('Suicide'),
('Suitan Wali Car'),
('Suit Burgundy'),
('Suit Patiala'),
('Suit Patiyala'),
('Suit Plazoo'),
('Suit Purane'),
('Suit'),
('Sukh Naal'),
('Summer'),
('Suni Chal'),
('Sunroof'),
('Sun Beba'),
('Sun Jattiye (feat. Manav Sidhu)'),
('Sun Le Saathiya'),
('Sun Le Zara'),
('Sun Sonio'),
('Sun Tatta Tatta'),
('Sun Yaara'),
('Sun Zara'),
('Super Te Upar'),
('Supna'),
('Supneya da Geet'),
('Supne Viah De'),
('Suraj'),
('Surma (From Alll Rounder)'),
('Surma'),
('Surma Kaala'),
('Surme Rangi'),
('Surname'),
('Surrender'),
('SURREY vs. MAJHA'),
('SURROOR 2021 TITLE TRACK'),
('Suthri Lage Se - Single'),
('Sukhri Si Chori 2'),
('Suzhaluren'),
('Swagy'),
('Swarz Life'),
('Sweety'),
('Swipe Right Material'),
('Taakre'),
('Taani Yaaran Di 2'),
('Taareyan De Naal'),
('Taareyan Naal Galbaat'),
('Taarifein'),
('Taaron Ke Shehar'),
('Shakeela'),
('Taaz'),
('Taa Vi Mardi'),
('Tabaahi'),
('Tagda Haryanvi Mashup 21'),
('Tainu Pata E Aa'),
('Tainu Waza'),
('Takdeer'),
('Takhte (Tunka Tunka)'),
('Takrar'),
('Talda Ni'),
('Talku Lessu Worku Moreu (From &quot;Murungakkai Chips&quot;)'),
('Talk Of The Town'),
('Tamancha Nach Re Sweety'),
('Tamatar'),
('Tanhaai'),
('Tanhaiyan'),
('Tanha Dil Tanha Safar'),
('Tanha Kyun'),
('Joshua Imai Pol Kaakha'),
('TARAKEE'),
('Tarasti Hain Nigahain'),
('Target'),
('Tasvi De Manke'),
('Taur'),
('Tedda Jatt'),
('Teddy Bear'),
('Tees Maar Khan'),
('TEG'),
('Teji Seat (feat. Kaka ji)'),
('Tell Me'),
('Tender'),
('Tenu Chad Ta'),
('Tenu Chete Karda'),
('Tenu Eda Bhullange'),
('Tenu Fer Pata Laghu'),
('Tenu Vekhan Da'),
('Tenu Yaad Karaan'),
('Tera Ban Jana'),
('Tera Dard'),
('Tera Deewana'),
('Tera Dil'),
('Tera Door Ni Canada'),
('Tera Fitoor'),
('Tera Hona Aaya'),
('Tera Hoon Na'),
('Tera Intezar'),
('Tera Ishq'),
('Tera Jikra'),
('Tera Mera Naata'),
('Tera Mera Pyar'),
('Tera Mera Viah'),
('Tera Ni Kasoor'),
('Tera Pyaar'),
('Tera Pyar'),
('Tera Sach'),
('Tera Sehar'),
('Tera Sharara'),
('Tera Shehar'),
('Tera Suit'),
('Tere Aala Saini'),
('Tere Bagairr'),
('Tere Bare About You'),
('Tere Bina'),
('Tere Bina Kaise Jiyu'),
('Tere Bin Jeena Nahi'),
('Tere Bin Zindagi'),
('Tere Hi Ghar Ke'),
('Tere Hi Hum'),
('Tere Jiha Hor Ni Koi'),
('Tere Karke'),
('Tere Ko Maloom Kya'),
('Tere Laare'),
('Tere Labh Pe'),
('Tere Mere Darmiyaan'),
('Tere Mere Mail Ho Gye'),
('Tere Naalon'),
('Tere Naal'),
('Tere Naal Rehniya'),
('Tere Naa Utte'),
('Tere Nashe Mein Choor'),
('Tere Noor Se'),
('Tere Pass'),
('Tere Pind'),
('Tere Saath'),
('Tere Sang'),
('Tere Tey Mardi'),
('Tere Ton Sohni'),
('Bollywood Hits Song 2021 - Pagalworld.com.se'),
('Tere Warga Munda'),
('Terii Umeed'),
('Teriyan Meriyan Laavan'),
('Teriyan Nishaniyan'),
('Teri Aadat'),
('Teri Aakhya Ka Yo Kajal'),
('Teri Aankhein Badi Anmol'),
('Teri Aankhon Mein'),
('Thalaivi'),
('Teri Ah'),
('Teri Akh'),
('Teri Baat Aur Hai'),
('Teri Choriyaan (From &quot;Chhalaang&quot;)'),
('Teri Deed'),
('Teri Galli Se'),
('Teri Insta Story'),
('Teri Judai'),
('Teri Life Meri Life'),
('Teri Load Ve'),
('Teri Maa'),
('Teri Meri Baat'),
('Indian Pop Mp3 Songs - PaglaSongs.Com'),
('Teri Need Ve'),
('Teri Ore'),
('Teri Rooh'),
('Teri Sadhgi'),
('Teri Tasveer'),
('Teri Yaari'),
('Terre Pyaar Mein'),
('Thala Kodhum (From &quot;Jai Bhim&quot;)'),
('Ranjish Hi Sahi'),
('Thandi Hawa'),
('Thandi Thandi'),
('Thand Rakh'),
('Thanimai'),
('Thanks to God'),
('Tharak'),
('Tharo Naam'),
('That&#039;s How I Feel'),
('Thats it'),
('Thats Why'),
('Maamanithan'),
('Thehra'),
('Theke Pe'),
('The Areaa'),
('The Baaz'),
('The Fuddu Song'),
('The Haryanvi Mashup 9'),
('The Haryanvi Mixtape'),
('The Haters'),
('The High Rated Mashup'),
('The Jatt'),
('The Proper Mashup'),
('The Villagers'),
('The Wedding'),
('The World We Left Behind (feat. KARRA)'),
('Thief'),
('Thikane'),
('Thik Thak'),
('Thiraiyoadu Thoorigai (From &quot;Radhe Shyam&quot;)'),
('Thoda Sa'),
('Thoda Thoda Hassi'),
('Thoda Thoda Pyaar'),
('Thodda Pyar'),
('Thodi Si Dua'),
('Thodi Si Raat Nashe'),
('Thokran'),
('Thok De Killi (From &quot;Time To Dance&quot;)'),
('Thug Life'),
('Thumka'),
('Thumke - Single'),
('Tibbeyan Da Putt'),
('Ticket Karwa De Piya'),
('Tiger Zinda Hai'),
('Tiktok'),
('Till Death'),
('Till I Die'),
('Timeless'),
('Timepass'),
('Time 2'),
('Time Ni Lagna'),
('Time On'),
('Time Paas'),
('Time'),
('Time To Dance Title Track  (From &quot;Time To Dance&quot;)'),
('Tim Horton'),
('Netrikann'),
('Shiddat Title Track (From &quot;Shiddat&quot;)'),
('Tohar Laal Laal Gaal'),
('Tohfa'),
('Tohfe (The Gift Of Love)'),
('Toh Aagaye Hum'),
('Tokk'),
('Tokni'),
('Tom &amp; Jerry'),
('Toofan'),
('Tootay'),
('Toota Taara'),
('Tootey Khaab'),
('Toot Jaayegi Aas'),
('Toot Jawenge'),
('Too Much'),
('Topiyan Nai Paiyan'),
('Topper 2021'),
('Top Notch Gabru'),
('Top Tucker'),
('Tora'),
('Toronto'),
('Toronto Vs Vancouver'),
('Totta Bhang Ka'),
('Touch Wood'),
('Touheen'),
('Town'),
('Town Vich'),
('To The Stars'),
('To The Warrior'),
('Traale Aale'),
('Tractor'),
('Tractor Ke Driver'),
('Tralla'),
('Tralle'),
('Transport'),
('Trending Jatti'),
('Trending'),
('Trigger'),
('Trolley'),
('Truck 2021'),
('True Love'),
('Trusted Jatti'),
('Truth'),
('Try Kar Ke'),
('Tujhe Bhoolna Toh Chaaha'),
('Tujhe Dekha'),
('Tujhe Dekha To - Kunal Bojewar'),
('Tujhe Janamdin Mubarak'),
('Tujhe Kitna Chahein Aur Acoustic'),
('Tujhe Paane Ko'),
('Tujh Mein Sukoon'),
('Tukur Tukur'),
('Tumhara Hone Laga'),
('Tumhari Jagga'),
('Tumhari Meri Baat'),
('Tumhari Yaad Ayee hai'),
('Tumpe Mar Jaaenge'),
('Tumsa Koi Pyaara'),
('Tumse Pyaar Hai'),
('Tum Aaoge'),
('Tum Bewafa Ho'),
('Tum Ho Mere Sanam'),
('Tum Ho'),
('Tum Itne Cute Kyun Ho (Female Version)'),
('Tum Itne Cute Kyun Ho (Male Version)'),
('Tum Kyu Chale Ate Ho'),
('Tum Na Ho'),
('Sanam - Tum Na Jane Kis Jahan Men Kho Gaye'),
('Pardesi Anthem 2020'),
('Tum Yun Hi Kabhi'),
('Tunn Karta'),
('Turban King'),
('Turkey'),
('Tuta Dil'),
('Tutti Bole'),
('Tu'),
('Tu Bhi Royega'),
('Tu Bhi Sataya Jayega'),
('Tu Dekhlai'),
('Tu Gori Mai Kala'),
('Tu Hai Toh'),
('Tu Hi Dil Jana'),
('Tu Hi Ik Tu'),
('Tu Hi Lagawa'),
('Tu Hi Mera Dil Hai'),
('Tu Hi Toh Hai Khuda'),
('Tu Item Videsi Hai'),
('Tu Itna Pyaara Kyu Se'),
('Tu Jatta Ve'),
('Tu Jo Kahe'),
('Tu Kahin Main Kahin'),
('Tu Kya Jaane'),
('Tu Lakh Nu Hilade'),
('Tu Mera Misra Hai'),
('Tu Mera Nahi'),
('Tu Mere Dil Main Rehta Hai'),
('Tu Mere Rubaru'),
('Tu Meri Ki Lagadi'),
('Tu Mileya'),
('Tu Milta Hai Mujhe'),
('Tu Nachna'),
('Tu Nasha'),
('Tu Online Hai'),
('Tu Rahe'),
('Tu Rovenga'),
('Tu Te Mai'),
('Tu Yaad Aya'),
('Tu Yaheen Hai'),
('Twinkle Twinkle'),
('Two Door'),
('T-Shirt'),
('Pisasu 2'),
('Uchiyaan Dewaraan'),
('Uchiyaan Dewaraan (Baari 2)'),
('Udaariyaan'),
('Udd Gaye Totte - Single'),
('Radhe Shyam - Hindi 2021'),
('Udeekan');
