USE USER;

INSERT IGNORE INTO Country (id, country, code)
VALUES
    (1, "Afghanistan", "AF"),
    (2, "Albania", "AL"),
    (3, "Armenia", "AM"),
    (4, "Australia", "AU"),
    (5, "Azerbaijan", "AZ"),
    (6, "Bangladesh", "BD"),
    (7, "Barbados", "BB"),
    (8, "Belgium", "BE"),
    (9, "Brazil", "BR"),
    (10, "Canada", "CA"),
    (11, "Colombia", "CO"),
    (12, "Czech Republic", "CZ"),
    (13, "Egypt", "EG"),
    (14, "France", "FR"),
    (15, "Georgia", "GE"),
    (16, "Germany", "DE"),
    (17, "Greece", "GR"),
    (18, "India", "IN"),
    (19, "Indonesia", "ID"),
    (20, "International", "ZZ"), -- not ISO, placeholder
    (21, "Iran", "IR"),
    (22, "Iraq", "IQ"),
    (23, "Israel", "IL"),
    (24, "Italy", "IT"),
    (25, "Jamaica", "JM"),
    (26, "Japan", "JP"),
    (27, "Jordan", "JO"),
    (28, "Kazakhstan", "KZ"),
    (29, "Kenya", "KE"),
    (30, "Latvia", "LV"),
    (31, "Lebanon", "LB"),
    (32, "Malaysia", "MY"),
    (33, "Maldives", "MV"),
    (34, "Mali", "ML"),
    (35, "Mexico", "MX"),
    (36, "Morocco", "MA"),
    (37, "Nepal", "NP"),
    (38, "Netherlands", "NL"),
    (39, "Nigeria", "NG"),
    (40, "Norway", "NO"),
    (41, "Pakistan", "PK"),
    (42, "Poland", "PL"),
    (43, "Portugal", "PT"),
    (44, "Puerto Rico", "PR"),
    (45, "Romania", "RO"),
    (46, "Russia", "RU"),
    (47, "Singapore", "SG"),
    (48, "South Africa", "ZA"),
    (49, "South Korea", "KR"),
    (50, "Spain", "ES"),
    (51, "Sri Lanka", "LK"),
    (52, "Sweden", "SE"),
    (53, "Syria", "SY"),
    (54, "Tanzania", "TZ"),
    (55, "Thailand", "TH"),
    (56, "Trinidad and Tobago", "TT"),
    (57, "Turkey", "TR"),
    (58, "United Arab Emirates", "AE"), -- keep only one UAE
    (61, "United Kingdom", "GB"),
    (62, "United States of America", "US"),
    (64, "Uzbekistan", "UZ"),
    (65, "Various", "XA"), -- placeholder
    (66, "West Indies", "XB"), -- placeholder
    (67, "Tajikistan", "TJ"),
    (68, "Denmark", "DK"),
    (69, "Herzegovina", "BA"), -- Bosnia & Herzegovina = BA
    (70, "Serbia", "RS"),
    (71, "Ghana", "GH"),
    (72, "New Zealand", "NZ");

INSERT IGNORE INTO UserType (id, `type`)
VALUES
    (1, 'GOOGLE'),
    (2, 'EMAIL');