USE Kyoku;

INSERT
IGNORE INTO Genre (id,`name`,cover) VALUES
(1, "Acoustic", "G:/rawGenreCover/Acoustic/"),
(2, "Actor", "G:/rawGenreCover/Actor/"),
(3, "Actress", "G:/rawGenreCover/Actress/"),
(4, "Afro-Pop", "G:/rawGenreCover/Afro-Pop/"),
(5, "Afrobeat", "G:/rawGenreCover/Afrobeat/"),
(6, "Albanian", "G:/rawGenreCover/Albanian/"),
(7, "Alternative", "G:/rawGenreCover/Alternative/"),
(8, "Arabic", "G:/rawGenreCover/Arabic/"),
(9, "Armenian", "G:/rawGenreCover/Armenian/"),
(10, "Assamese", "G:/rawGenreCover/Assamese/"),
(11, "Balochi", "G:/rawGenreCover/Balochi/"),
(12, "Bengali", "G:/rawGenreCover/Bengali/"),
(13, "Bhajan", "G:/rawGenreCover/Bhajan/"),
(14, "Bhangra", "G:/rawGenreCover/Bhangra/"),
(15, "Bhojpuri", NULL),
(16, "Blues", "G:/rawGenreCover/Blues/"),
(17, "Bollywood", "G:/rawGenreCover/Bollywood/"),
(18, "Carnatic", "G:/rawGenreCover/Carnatic/"),
(19, "Chhattisgarhi", "G:/rawGenreCover/Chhattisgarhi/"),
(20, "Children's Music", "G:/rawGenreCover/Children's Music/"),
(21, "Choir", "G:/rawGenreCover/Choir/"),
(22, "Choral", "G:/rawGenreCover/Choral/"),
(23, "Christian", "G:/rawGenreCover/Christian/"),
(24, "Chutney", "G:/rawGenreCover/Chutney/"),
(25, "Classical", "G:/rawGenreCover/Classical/"),
(26, "Comedy", "G:/rawGenreCover/Comedy/"),
(27, "Country", "G:/rawGenreCover/Country/"),
(28, "Dance", "G:/rawGenreCover/Dance/"),
(29, "Dancehall", NULL),
(30, "Devotional", "G:/rawGenreCover/Sikh Devotional/"),
(31, "DJ", "G:/rawGenreCover/DJ/"),
(32, "Dubstep", NULL),
(33, "EDM", "G:/rawGenreCover/EDM/"),
(34, "Electronic", "G:/rawGenreCover/Electronic/"),
(35, "English", NULL),
(36, "Fado", "G:/rawGenreCover/Fado/"),
(37, "Film", NULL),
(38, "Flute", "G:/rawGenreCover/Flute/"),
(39, "Folk", "G:/rawGenreCover/Folk/"),
(40, "French", NULL),
(41, "Fusion", "G:/rawGenreCover/Fusion/"),
(42, "German", "G:/rawGenreCover/German/"),
(43, "Ghazal", "G:/rawGenreCover/Ghazal/"),
(44, "Gospel", "G:/rawGenreCover/Gospel/"),
(45, "Greek", "G:/rawGenreCover/Greek/"),
(46, "Grime", "G:/rawGenreCover/Grime/"),
(47, "Gujarati", "G:/rawGenreCover/Gujarati/"),
(48, "Haryanvi", "G:/rawGenreCover/Haryanvi/"),
(49, "Hindi", "G:/rawGenreCover/Hindi/"),
(50, "Hindustani", "G:/rawGenreCover/Hindustani/"),
(51, "Hip Hop", "G:/rawGenreCover/Hip Hop/"),
(52, "House", "G:/rawGenreCover/House/"),
(53, "Indian", "G:/rawGenreCover/Indian/"),
(54, "Indian Classical", "G:/rawGenreCover/Indian Classical/"),
(55, "Indie", "G:/rawGenreCover/Indie/"),
(56, "Instrumental", "G:/rawGenreCover/Instrumental/"),
(57, "Italian", NULL),
(58, "J-Pop", "G:/rawGenreCover/J-Pop/"),
(59, "Jazz", "G:/rawGenreCover/Jazz/"),
(60, "K-pop", "G:/rawGenreCover/K-pop/"),
(61, "Kannada", NULL),
(62, "Kashmiri", "G:/rawGenreCover/Kashmiri/"),
(63, "Kirtan", "G:/rawGenreCover/Kirtan/"),
(64, "Konkani", NULL),
(65, "Korean", "G:/rawGenreCover/Korean/"),
(66, "Kurdish", NULL),
(67, "Latin", "G:/rawGenreCover/Latin/"),
(68, "Latin Trap", "G:/rawGenreCover/Latin Trap/"),
(69, "Latvian Folk", NULL),
(70, "Malayalam", "G:/rawGenreCover/Malayalam/"),
(71, "Manipuri", "G:/rawGenreCover/Manipuri/"),
(72, "Marathi", "G:/rawGenreCover/Marathi/"),
(73, "Metal", "G:/rawGenreCover/Metal/"),
(74, "Naat", "G:/rawGenreCover/Naat/"),
(75, "Nepali", "G:/rawGenreCover/Nepali/"),
(76, "Odia", "G:/rawGenreCover/Odia/"),
(77, "Pakistani", NULL),
(78, "Pashto", "G:/rawGenreCover/Pashto/"),
(79, "Persian", "G:/rawGenreCover/Persian/"),
(80, "Playback", NULL),
(81, "Poetry", "G:/rawGenreCover/Poetry/"),
(82, "Politics", "G:/rawGenreCover/Politics/"),
(83, "Pop", "G:/rawGenreCover/Afro-Pop/"),
(84, "Portuguese", "G:/rawGenreCover/Portuguese/"),
(85, "Producer", "G:/rawGenreCover/Producer/"),
(86, "Punjabi", "G:/rawGenreCover/Punjabi/"),
(87, "Qawwali", "G:/rawGenreCover/Qawwali/"),
(88, "R&B", NULL),
(89, "Rajasthani", "G:/rawGenreCover/Rajasthani/"),
(90, "Rap", "G:/rawGenreCover/Rap/"),
(91, "Reggae", NULL),
(92, "Reggaeton", NULL),
(93, "Remix", "G:/rawGenreCover/Remix/"),
(94, "Rock", "G:/rawGenreCover/Rock/"),
(95, "Romanian", "G:/rawGenreCover/Romanian/"),
(96, "Sanskrit", "G:/rawGenreCover/Sanskrit/"),
(97, "Santali", NULL),
(98, "Sertanejo", NULL),
(99, "Sikh Devotional", "G:/rawGenreCover/Sikh Devotional/"),
(100, "Sindhi", NULL),
(101, "Sinhala", "G:/rawGenreCover/Sinhala/"),
(102, "Soul", "G:/rawGenreCover/Soul/"),
(103, "Soundtrack", "G:/rawGenreCover/Soundtrack/"),
(104, "Spanish", "G:/rawGenreCover/Spanish/"),
(105, "Speech", "G:/rawGenreCover/Speech/"),
(106, "Spiritual", "G:/rawGenreCover/Spiritual/"),
(107, "Spoken Word", NULL),
(108, "Sufi", "G:/rawGenreCover/Sufi/"),
(109, "Swahili", "G:/rawGenreCover/Swahili/"),
(110, "Swedish", "G:/rawGenreCover/Swedish/"),
(111, "Tamil", "G:/rawGenreCover/Tamil/"),
(112, "Telugu", "G:/rawGenreCover/Telugu/"),
(113, "Thai", "G:/rawGenreCover/Thai/"),
(114, "Trance", "G:/rawGenreCover/Trance/"),
(115, "Turkish", "G:/rawGenreCover/Turkish/"),
(116, "Urban", "G:/rawGenreCover/Urban/"),
(117, "Urdu", "G:/rawGenreCover/Urdu/"),
(118, "Various", NULL),
(119, "Western Classical", "G:/rawGenreCover/Western Classical/"),
(120, "World", NULL),
(121, "Babul", "G:/rawGenreCover/Babul/");