package com.poulastaa.common.ui.design_system

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFD97706)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE4B8)
val onPrimaryContainerLight = Color(0xFF462400)
val secondaryLight = Color(0xFF6A5844)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF5E0CC)
val onSecondaryContainerLight = Color(0xFF4A3828)
val tertiaryLight = Color(0xFF8C4A46)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9D6)
val onTertiaryContainerLight = Color(0xFF5A1E1C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF1E9)
val onBackgroundLight = Color(0xFF1E1710)
val surfaceLight = Color(0xFFFFF1E9)
val onSurfaceLight = Color(0xFF1E1710)
val surfaceVariantLight = Color(0xFFEEE0D0)
val onSurfaceVariantLight = Color(0xFF4A3C32)
val outlineLight = Color(0xFF7A6558)
val outlineVariantLight = Color(0xFFD2BFAD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342E24)
val inverseOnSurfaceLight = Color(0xFFF9EDE0)
val inversePrimaryLight = Color(0xFFE8A820)
val surfaceDimLight = Color(0xFFE0D2C0)
val surfaceBrightLight = Color(0xFFFFF1E9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFEEDE0)
val surfaceContainerLight = Color(0xFFF8E6D8)
val surfaceContainerHighLight = Color(0xFFF2E0D0)
val surfaceContainerHighestLight = Color(0xFFECDACC)

// =============================================================
//  LIGHT — MEDIUM CONTRAST
// =============================================================

val primaryLightMediumContrast = Color(0xFF7A4400)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA46400)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF463428)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF7C6450)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF581E1B)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9E5854)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF1E9)
val onBackgroundLightMediumContrast = Color(0xFF1E1710)
val surfaceLightMediumContrast = Color(0xFFFFF1E9)
val onSurfaceLightMediumContrast = Color(0xFF120E08)
val surfaceVariantLightMediumContrast = Color(0xFFEEE0D0)
val onSurfaceVariantLightMediumContrast = Color(0xFF382C22)
val outlineLightMediumContrast = Color(0xFF5A4838)
val outlineVariantLightMediumContrast = Color(0xFF766252)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF342E24)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF9EDE0)
val inversePrimaryLightMediumContrast = Color(0xFFE8A820)
val surfaceDimLightMediumContrast = Color(0xFFCEC0AE)
val surfaceBrightLightMediumContrast = Color(0xFFFFF1E9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFEEDE0)
val surfaceContainerLightMediumContrast = Color(0xFFF2E0D0)
val surfaceContainerHighLightMediumContrast = Color(0xFFE4D4C2)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD8C8B6)

// =============================================================
//  LIGHT — HIGH CONTRAST
// =============================================================

val primaryLightHighContrast = Color(0xFF3A1E00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF683600)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF342018)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF584432)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3C1210)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF6A2D2A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF1E9)
val onBackgroundLightHighContrast = Color(0xFF1E1710)
val surfaceLightHighContrast = Color(0xFFFFF1E9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEEE0D0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2E2218)
val outlineVariantLightHighContrast = Color(0xFF4A3830)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF342E24)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE8A820)
val surfaceDimLightHighContrast = Color(0xFFBFAF9E)
val surfaceBrightLightHighContrast = Color(0xFFFFF1E9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF9EDE0)
val surfaceContainerLightHighContrast = Color(0xFFECDACC)
val surfaceContainerHighLightHighContrast = Color(0xFFDECEBE)
val surfaceContainerHighestLightHighContrast = Color(0xFFD0C2B2)

// =============================================================
//  DARK THEME
//  Primary  : #E8A820  — warm gold
//  BG/Surf  : #0E0E0B  — near-black, warm undertone
//  Secondary: #B8A890  — warm mushroom  (low chroma, taupe — clearly subordinate to gold)
//  Tertiary : #C49490  — dusty rose     (moody, warm — late-night listening energy)
// =============================================================

val primaryDark = Color(0xFFE8A820)
val onPrimaryDark = Color(0xFF1A0C00)
val primaryContainerDark = Color(0xFF4A3600)
val onPrimaryContainerDark = Color(0xFFFFDF9E)
val secondaryDark = Color(0xFFB8A890)
val onSecondaryDark = Color(0xFF201810)
val secondaryContainerDark = Color(0xFF322820)
val onSecondaryContainerDark = Color(0xFFD8C8B8)
val tertiaryDark = Color(0xFFC49490)
val onTertiaryDark = Color(0xFF1E1010)
val tertiaryContainerDark = Color(0xFF481E1C)
val onTertiaryContainerDark = Color(0xFFE8C4C0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E0E0B)
val onBackgroundDark = Color(0xFFEDE4D6)
val surfaceDark = Color(0xFF0E0E0B)
val onSurfaceDark = Color(0xFFEDE4D6)
val surfaceVariantDark = Color(0xFF382E26)
val onSurfaceVariantDark = Color(0xFFC8B8A6)
val outlineDark = Color(0xFF9A8878)
val outlineVariantDark = Color(0xFF382E26)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEDE4D6)
val inverseOnSurfaceDark = Color(0xFF2B2620)
val inversePrimaryDark = Color(0xFF7A5000)
val surfaceDimDark = Color(0xFF0E0E0B)
val surfaceBrightDark = Color(0xFF363028)
val surfaceContainerLowestDark = Color(0xFF090906)
val surfaceContainerLowDark = Color(0xFF171410)
val surfaceContainerDark = Color(0xFF1C1812)
val surfaceContainerHighDark = Color(0xFF272219)
val surfaceContainerHighestDark = Color(0xFF332C24)

// =============================================================
//  DARK — MEDIUM CONTRAST
// =============================================================

val primaryDarkMediumContrast = Color(0xFFFFCA6A)
val onPrimaryDarkMediumContrast = Color(0xFF2C1500)
val primaryContainerDarkMediumContrast = Color(0xFFB07C10)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD4C0A8)
val onSecondaryDarkMediumContrast = Color(0xFF160E06)
val secondaryContainerDarkMediumContrast = Color(0xFF8A7868)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD8ACAA)
val onTertiaryDarkMediumContrast = Color(0xFF140608)
val tertiaryContainerDarkMediumContrast = Color(0xFF8E6664)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E0E0B)
val onBackgroundDarkMediumContrast = Color(0xFFEDE4D6)
val surfaceDarkMediumContrast = Color(0xFF0E0E0B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF382E26)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDACBBB)
val outlineDarkMediumContrast = Color(0xFFB0A092)
val outlineVariantDarkMediumContrast = Color(0xFF9A8878)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEDE4D6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272219)
val inversePrimaryDarkMediumContrast = Color(0xFF5E3C00)
val surfaceDimDarkMediumContrast = Color(0xFF0E0E0B)
val surfaceBrightDarkMediumContrast = Color(0xFF423C34)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF060604)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1712)
val surfaceContainerDarkMediumContrast = Color(0xFF252119)
val surfaceContainerHighDarkMediumContrast = Color(0xFF302C23)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C362D)

// =============================================================
//  DARK — HIGH CONTRAST
// =============================================================

val primaryDarkHighContrast = Color(0xFFFFEED4)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE3A41C)
val onPrimaryContainerDarkHighContrast = Color(0xFF100600)
val secondaryDarkHighContrast = Color(0xFFFFEED4)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC0AE9C)
val onSecondaryContainerDarkHighContrast = Color(0xFF0A0604)
val tertiaryDarkHighContrast = Color(0xFFFFE4E2)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC09090)
val onTertiaryContainerDarkHighContrast = Color(0xFF0D0101)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E0E0B)
val onBackgroundDarkHighContrast = Color(0xFFEDE4D6)
val surfaceDarkHighContrast = Color(0xFF0E0E0B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF382E26)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF4E6D2)
val outlineVariantDarkHighContrast = Color(0xFFC0AE9C)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEDE4D6)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF5E3C00)
val surfaceDimDarkHighContrast = Color(0xFF0E0E0B)
val surfaceBrightDarkHighContrast = Color(0xFF4E4840)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C1812)
val surfaceContainerDarkHighContrast = Color(0xFF2B2620)
val surfaceContainerHighDarkHighContrast = Color(0xFF37312A)
val surfaceContainerHighestDarkHighContrast = Color(0xFF433D35)