insert ignore into genre (genre) values 
	(' Bollywood'),
    (' Electronic'),
    (' Pop'),
    (' Pakistani Pop'),
    (' Pakistani Hip-Hop'),
    (' Qawwali'),
    (' Punjabi'),
    (' Ghazal'),
    (' Devotional'),
    (' Hip-Hop'),
    (' Afrobeats'),
    (' Bhojpuri'),
    (' Folk'),
    (' Indie Pop'),
    (' Persian'),
    (' Tamil'),
    (' Arabic'),
    (' Urban Desi'),
    (' Haryanvi'),
    (' Bangla'),
    (' Reggae'),
    (' Telugu'),
    (' Indi-Pop'),
    (' Urdu'),
    (' Marathi'),
    (' Rap'),
    (' Odia'),
    (' Nepali'),
    (' Classical'),
    (' Hindi'),
    (' Malayalam'),
    (' Kannada'),
    (' K-pop'),
    (' Gujarati'),
    (' Carnatic'),
    (' Rajasthani'),
    (' Indie'),
    (' Playback'),
    (' Film Score'),
    (' Hip Hop'),
    (' Tollywood'),
    (' Remix'),
    (' Lyricist'),
    (' R&B'),
    (' Kashmiri'),
    (' Hindi Rap'),
    (' Sufi'),
    (' Bengali'),
    (' Pakistani'),
    (' Indian Classical'),
    (' Bhangra'),
    (' Dance'),
    (' Reggaeton'),
    (' Country'),
    (' Rock'),
    (' Balochi'),
    (' Afrobeat'),
    (' Instrumental'),
    (' Indian Hip Hop'),
    (' EDM'),
    (' Comedy'),
    (' Hindi Pop'),
    (' Urban'),
    (' Pashto'),
    (' English'),
    (' Various'),
    (' Indian'),
    (' Assamese'),
    (' Dutch');