Insert into genre (name) values 
('Kyokui.Com'),
('Kyoku.Com'),
('Kyoku'),
('Bollywood'),
('Tamil'),
('Punjabi'),
('Indipop'),
('Jalwa'),
('Hindi'),
('Ragni 18+'),
('Bhojpuri'),
('Rang Malak De (From &quot;Lehmberginni&quot;)'),
('Rang Tera (From &quot;Lehmberginni&quot;)'),
('Raniya (From &quot;Kade Dade Diyan Kade Pote Diyan&quot;)'),
('Ready'),
('Yutha Satham'),
('Indian Pop'),
('Bollwood'),
('Rukka Dhani Me (feat. Vijay Varma &amp; Anjali Raghav)'),
('Haryanvi'),
('Prithviraj'),
('Another Side'),
('Devotional'),
('Slayer (feat. Bhallwaan'),
('Sonrisa'),
('Swaal (From &quot;Vajood&quot;)'),
('Tareefan'),
('Teri Hoi Na Hundi (From &quot;Zindagi Zindabaad&quot;)'),
('Adiyae'),
('Babe Bhangra Paunde Ne - Title Track (From &quot;Babe Bhangra Paunde Ne&quot;)'),
('Sab Moh Maaya Hai (Title Track) (From &quot;Sab Moh Maaya Hai&quot;)'),
('Udeekan Teriyaan (From &quot;Udeekan Teriyaan&quot;)'),
('Tumhe Kitna Pyaar Karte (From &quot;Bawaal&quot;)'),
('Twinkle Twinkle (From &quot;Lehmberginni&quot;)'),
('Gadar 2'),
('Vattam Thaan'),
('We Run Things (From an EP &quot;Yallah Habibi&quot;)'),
('Rangoli'),
('Zara (From &quot;Farhana&quot;)'),
('English'),
('Dhan Dhan Mata Gujri Ji (Daadi Ji 2)'),
('Dj Mix Mashup Song'),
('Kyoku.To'),
('Hijab'),
('Club'),
('PaglaSongs.Com'),
('Electronic'),
('Pop'),
('Pakistani Pop'),
('Pakistani Hip-Hop'),
('Qawwali'),
('Ghazal'),
('Hip-Hop'),
('Afrobeats'),
('Folk'),
('Indie Pop'),
('Persian'),
('Arabic'),
('Urban Desi'),
('Bangla'),
('Reggae'),
('Telugu'),
('Indi-Pop'),
('Urdu'),
('Marathi'),
('Rap'),
('Odia'),
('Nepali'),
('Classical'),
('Malayalam'),
('Kannada'),
('K-pop'),
('Gujarati'),
('Carnatic'),
('Rajasthani'),
('Indie'),
('Playback'),
('Film Score'),
('Hip Hop'),
('Tollywood'),
('Remix'),
('Lyricist'),
('R&B'),
('Kashmiri'),
('Hindi Rap'),
('Sufi'),
('Bengali'),
('Pakistani'),
('Indian Classical'),
('Bhangra'),
('Dance'),
('Reggaeton'),
('Country'),
('Rock'),
('Balochi'),
('Afrobeat'),
('Instrumental'),
('Indian Hip Hop'),
('EDM'),
('Comedy'),
('Hindi Pop'),
('Urban'),
('Pashto'),
('Various'),
('Indian'),
('Assamese'),
('Dutch');
