syntax = "proto3";
import "model.proto";

option java_multiple_files = true;
option java_package = "com.poulastaa.kyoku.grpc.gateway_playlist";

package gatewayPlaylist;

message RequestGetPlaylist{
  string playlistId = 1;
  model.RequestUser user = 2;
};

// response
message ResponsePlaylist{
  int64 playlistId = 1;
  string name = 2;
  int64 popularity = 3;
  ResponsePlaylistVisibilityState status = 4;

  enum ResponsePlaylistVisibilityState{
    PUBLIC = 0;
    PRIVATE = 1;
  };
};

message ResponseSong{
  int64 id = 1;
  string title = 2;
  optional string poster = 3;
  string masterPlaylist = 4;
  model.SongInfo info = 5;
  repeated model.Artist artists = 6;
  repeated model.Genre genre = 7;
  repeated model.Country country = 8;
};

message ResponseFullPlaylist{
  ResponsePlaylist playlist = 1;
  repeated ResponseSong songs = 2;
};


service GatewayPlaylistService{
  rpc getPlaylist(RequestGetPlaylist) returns (ResponseFullPlaylist);
}