package com.poulastaa.kyoku.ui.theme

import androidx.compose.ui.graphics.Color

val light_type_one_primary = Color(0xFF006C4E)
val light_type_one_onPrimary = Color(0xFFFFFFFF)
val light_type_one_primaryContainer = Color(0xFF87F8C9)
val light_type_one_onPrimaryContainer = Color(0xFF002115)
val light_type_one_secondary = Color(0xFF4C6358)
val light_type_one_onSecondary = Color(0xFFFFFFFF)
val light_type_one_secondaryContainer = Color(0xFFCFE9DA)
val light_type_one_onSecondaryContainer = Color(0xFF092017)
val light_type_one_tertiary = Color(0xFF3E6374)
val light_type_one_onTertiary = Color(0xFFFFFFFF)
val light_type_one_tertiaryContainer = Color(0xFFC1E8FC)
val light_type_one_onTertiaryContainer = Color(0xFF001F2A)
val light_type_one_error = Color(0xFFBA1A1A)
val light_type_one_errorContainer = Color(0xFFFFDAD6)
val light_type_one_onError = Color(0xFFFFFFFF)
val light_type_one_onErrorContainer = Color(0xFF410002)
val light_type_one_background = Color(0xFFFBFDF9)
val light_type_one_onBackground = Color(0xFF191C1A)
val light_type_one_surface = Color(0xFFFBFDF9)
val light_type_one_onSurface = Color(0xFF191C1A)
val light_type_one_surfaceVariant = Color(0xFFDBE5DE)
val light_type_one_onSurfaceVariant = Color(0xFF404944)
val light_type_one_outline = Color(0xFF707973)
val light_type_one_inverseOnSurface = Color(0xFFEFF1ED)
val light_type_one_inverseSurface = Color(0xFF2E312F)
val light_type_one_inversePrimary = Color(0xFF69DBAE)
val light_type_one_shadow = Color(0xFF000000)
val light_type_one_surfaceTint = Color(0xFF006C4E)
val light_type_one_outlineVariant = Color(0xFFBFC9C2)
val light_type_one_scrim = Color(0xFF000000)

val dark_type_one_primary = Color(0xFF69DBAE)
val dark_type_one_onPrimary = Color(0xFF003827)
val dark_type_one_primaryContainer = Color(0xFF00513A)
val dark_type_one_onPrimaryContainer = Color(0xFF87F8C9)
val dark_type_one_secondary = Color(0xFFB3CCBE)
val dark_type_one_onSecondary = Color(0xFF1F352B)
val dark_type_one_secondaryContainer = Color(0xFF354B41)
val dark_type_one_onSecondaryContainer = Color(0xFFCFE9DA)
val dark_type_one_tertiary = Color(0xFFA6CCDF)
val dark_type_one_onTertiary = Color(0xFF083544)
val dark_type_one_tertiaryContainer = Color(0xFF254B5B)
val dark_type_one_onTertiaryContainer = Color(0xFFC1E8FC)
val dark_type_one_error = Color(0xFFFFB4AB)
val dark_type_one_errorContainer = Color(0xFF93000A)
val dark_type_one_onError = Color(0xFF690005)
val dark_type_one_onErrorContainer = Color(0xFFFFDAD6)
val dark_type_one_background = Color(0xFF191C1A)
val dark_type_one_onBackground = Color(0xFFE1E3DF)
val dark_type_one_surface = Color(0xFF191C1A)
val dark_type_one_onSurface = Color(0xFFE1E3DF)
val dark_type_one_surfaceVariant = Color(0xFF404944)
val dark_type_one_onSurfaceVariant = Color(0xFFBFC9C2)
val dark_type_one_outline = Color(0xFF89938D)
val dark_type_one_inverseOnSurface = Color(0xFF191C1A)
val dark_type_one_inverseSurface = Color(0xFFE1E3DF)
val dark_type_one_inversePrimary = Color(0xFF006C4E)
val dark_type_one_shadow = Color(0xFF000000)
val dark_type_one_surfaceTint = Color(0xFF69DBAE)
val dark_type_one_outlineVariant = Color(0xFF404944)
val dark_type_one_scrim = Color(0xFF000000)


val seed_type_one = Color(0xFF006C4E)




val light_type_two_primary = Color(0xFF7C5800)
val light_type_two_onPrimary = Color(0xFFFFFFFF)
val light_type_two_primaryContainer = Color(0xFFFFDEA7)
val light_type_two_onPrimaryContainer = Color(0xFF271900)
val light_type_two_secondary = Color(0xFF6D5C3F)
val light_type_two_onSecondary = Color(0xFFFFFFFF)
val light_type_two_secondaryContainer = Color(0xFFF7DFBB)
val light_type_two_onSecondaryContainer = Color(0xFF251A04)
val light_type_two_tertiary = Color(0xFF4D6544)
val light_type_two_onTertiary = Color(0xFFFFFFFF)
val light_type_two_tertiaryContainer = Color(0xFFCFEBC1)
val light_type_two_onTertiaryContainer = Color(0xFF0B2007)
val light_type_two_error = Color(0xFFBA1A1A)
val light_type_two_errorContainer = Color(0xFFFFDAD6)
val light_type_two_onError = Color(0xFFFFFFFF)
val light_type_two_onErrorContainer = Color(0xFF410002)
val light_type_two_background = Color(0xFFFFFBFF)
val light_type_two_onBackground = Color(0xFF1E1B16)
val light_type_two_surface = Color(0xFFFFFBFF)
val light_type_two_onSurface = Color(0xFF1E1B16)
val light_type_two_surfaceVariant = Color(0xFFEEE1CF)
val light_type_two_onSurfaceVariant = Color(0xFF4E4639)
val light_type_two_outline = Color(0xFF807667)
val light_type_two_inverseOnSurface = Color(0xFFF8EFE7)
val light_type_two_inverseSurface = Color(0xFF34302A)
val light_type_two_inversePrimary = Color(0xFFF7BD48)
val light_type_two_shadow = Color(0xFF000000)
val light_type_two_surfaceTint = Color(0xFF7C5800)
val light_type_two_outlineVariant = Color(0xFFD1C5B4)
val light_type_two_scrim = Color(0xFF000000)

val dark_type_two_primary = Color(0xFFF7BD48)
val dark_type_two_onPrimary = Color(0xFF412D00)
val dark_type_two_primaryContainer = Color(0xFF5E4200)
val dark_type_two_onPrimaryContainer = Color(0xFFFFDEA7)
val dark_type_two_secondary = Color(0xFFDAC4A0)
val dark_type_two_onSecondary = Color(0xFF3C2E15)
val dark_type_two_secondaryContainer = Color(0xFF54452A)
val dark_type_two_onSecondaryContainer = Color(0xFFF7DFBB)
val dark_type_two_tertiary = Color(0xFFB3CEA6)
val dark_type_two_onTertiary = Color(0xFF203619)
val dark_type_two_tertiaryContainer = Color(0xFF354D2E)
val dark_type_two_onTertiaryContainer = Color(0xFFCFEBC1)
val dark_type_two_error = Color(0xFFFFB4AB)
val dark_type_two_errorContainer = Color(0xFF93000A)
val dark_type_two_onError = Color(0xFF690005)
val dark_type_two_onErrorContainer = Color(0xFFFFDAD6)
val dark_type_two_background = Color(0xFF1E1B16)
val dark_type_two_onBackground = Color(0xFFE9E1D9)
val dark_type_two_surface = Color(0xFF1E1B16)
val dark_type_two_onSurface = Color(0xFFE9E1D9)
val dark_type_two_surfaceVariant = Color(0xFF4E4639)
val dark_type_two_onSurfaceVariant = Color(0xFFD1C5B4)
val dark_type_two_outline = Color(0xFF9A8F80)
val dark_type_two_inverseOnSurface = Color(0xFF1E1B16)
val dark_type_two_inverseSurface = Color(0xFFE9E1D9)
val dark_type_two_inversePrimary = Color(0xFF7C5800)
val dark_type_two_shadow = Color(0xFF000000)
val dark_type_two_surfaceTint = Color(0xFFF7BD48)
val dark_type_two_outlineVariant = Color(0xFF4E4639)
val dark_type_two_scrim = Color(0xFF000000)


val seed_type_two = Color(0xFF7C5800)

