package com.poulastaa.kyoku.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val LightColorSchemeTypeOne = lightColorScheme(
    primary = light_type_one_primary,
    onPrimary = light_type_one_onPrimary,
    primaryContainer = light_type_one_primaryContainer,
    onPrimaryContainer = light_type_one_onPrimaryContainer,
    secondary = light_type_one_secondary,
    onSecondary = light_type_one_onSecondary,
    secondaryContainer = light_type_one_secondaryContainer,
    onSecondaryContainer = light_type_one_onSecondaryContainer,
    tertiary = light_type_one_tertiary,
    onTertiary = light_type_one_onTertiary,
    tertiaryContainer = light_type_one_tertiaryContainer,
    onTertiaryContainer = light_type_one_onTertiaryContainer,
    error = light_type_one_error,
    errorContainer = light_type_one_errorContainer,
    onError = light_type_one_onError,
    onErrorContainer = light_type_one_onErrorContainer,
    background = light_type_one_background,
    onBackground = light_type_one_onBackground,
    surface = light_type_one_surface,
    onSurface = light_type_one_onSurface,
    surfaceVariant = light_type_one_surfaceVariant,
    onSurfaceVariant = light_type_one_onSurfaceVariant,
    outline = light_type_one_outline,
    inverseOnSurface = light_type_one_inverseOnSurface,
    inverseSurface = light_type_one_inverseSurface,
    inversePrimary = light_type_one_inversePrimary,
    surfaceTint = light_type_one_surfaceTint,
    outlineVariant = light_type_one_outlineVariant,
    scrim = light_type_one_scrim,
)

val DarkColorSchemeTypeOne = darkColorScheme(
    primary = dark_type_one_primary,
    onPrimary = dark_type_one_onPrimary,
    primaryContainer = dark_type_one_primaryContainer,
    onPrimaryContainer = dark_type_one_onPrimaryContainer,
    secondary = dark_type_one_secondary,
    onSecondary = dark_type_one_onSecondary,
    secondaryContainer = dark_type_one_secondaryContainer,
    onSecondaryContainer = dark_type_one_onSecondaryContainer,
    tertiary = dark_type_one_tertiary,
    onTertiary = dark_type_one_onTertiary,
    tertiaryContainer = dark_type_one_tertiaryContainer,
    onTertiaryContainer = dark_type_one_onTertiaryContainer,
    error = dark_type_one_error,
    errorContainer = dark_type_one_errorContainer,
    onError = dark_type_one_onError,
    onErrorContainer = dark_type_one_onErrorContainer,
    background = dark_type_one_background,
    onBackground = dark_type_one_onBackground,
    surface = dark_type_one_surface,
    onSurface = dark_type_one_onSurface,
    surfaceVariant = dark_type_one_surfaceVariant,
    onSurfaceVariant = dark_type_one_onSurfaceVariant,
    outline = dark_type_one_outline,
    inverseOnSurface = dark_type_one_inverseOnSurface,
    inverseSurface = dark_type_one_inverseSurface,
    inversePrimary = dark_type_one_inversePrimary,
    surfaceTint = dark_type_one_surfaceTint,
    outlineVariant = dark_type_one_outlineVariant,
    scrim = dark_type_one_scrim,
)



val LightColorSchemeTypeTwo = lightColorScheme(
    primary = light_type_two_primary,
    onPrimary = light_type_two_onPrimary,
    primaryContainer = light_type_two_primaryContainer,
    onPrimaryContainer = light_type_two_onPrimaryContainer,
    secondary = light_type_two_secondary,
    onSecondary = light_type_two_onSecondary,
    secondaryContainer = light_type_two_secondaryContainer,
    onSecondaryContainer = light_type_two_onSecondaryContainer,
    tertiary = light_type_two_tertiary,
    onTertiary = light_type_two_onTertiary,
    tertiaryContainer = light_type_two_tertiaryContainer,
    onTertiaryContainer = light_type_two_onTertiaryContainer,
    error = light_type_two_error,
    errorContainer = light_type_two_errorContainer,
    onError = light_type_two_onError,
    onErrorContainer = light_type_two_onErrorContainer,
    background = light_type_two_background,
    onBackground = light_type_two_onBackground,
    surface = light_type_two_surface,
    onSurface = light_type_two_onSurface,
    surfaceVariant = light_type_two_surfaceVariant,
    onSurfaceVariant = light_type_two_onSurfaceVariant,
    outline = light_type_two_outline,
    inverseOnSurface = light_type_two_inverseOnSurface,
    inverseSurface = light_type_two_inverseSurface,
    inversePrimary = light_type_two_inversePrimary,
    surfaceTint = light_type_two_surfaceTint,
    outlineVariant = light_type_two_outlineVariant,
    scrim = light_type_two_scrim,
)


val DarkColorSchemeTypeTwo = darkColorScheme(
    primary = dark_type_two_primary,
    onPrimary = dark_type_two_onPrimary,
    primaryContainer = dark_type_two_primaryContainer,
    onPrimaryContainer = dark_type_two_onPrimaryContainer,
    secondary = dark_type_two_secondary,
    onSecondary = dark_type_two_onSecondary,
    secondaryContainer = dark_type_two_secondaryContainer,
    onSecondaryContainer = dark_type_two_onSecondaryContainer,
    tertiary = dark_type_two_tertiary,
    onTertiary = dark_type_two_onTertiary,
    tertiaryContainer = dark_type_two_tertiaryContainer,
    onTertiaryContainer = dark_type_two_onTertiaryContainer,
    error = dark_type_two_error,
    errorContainer = dark_type_two_errorContainer,
    onError = dark_type_two_onError,
    onErrorContainer = dark_type_two_onErrorContainer,
    background = dark_type_two_background,
    onBackground = dark_type_two_onBackground,
    surface = dark_type_two_surface,
    onSurface = dark_type_two_onSurface,
    surfaceVariant = dark_type_two_surfaceVariant,
    onSurfaceVariant = dark_type_two_onSurfaceVariant,
    outline = dark_type_two_outline,
    inverseOnSurface = dark_type_two_inverseOnSurface,
    inverseSurface = dark_type_two_inverseSurface,
    inversePrimary = dark_type_two_inversePrimary,
    surfaceTint = dark_type_two_surfaceTint,
    outlineVariant = dark_type_two_outlineVariant,
    scrim = dark_type_two_scrim,
)